import type { McqQuestion } from "@/domain/exam";

/** AWS architecture scenarios — pick the right service for the situation. */
export const mcqAwsBank: McqQuestion[] = [
  {
    id: "aws-rds-managed-db",
    prompt:
      "You need a managed relational DB with automated backups, Multi-AZ HA, and AWS-handled patching. Best choice?",
    options: [
      { id: "a", label: "Amazon RDS (or Aurora)" },
      { id: "b", label: "EC2 + self-installed MySQL with no managed backups" },
      { id: "c", label: "S3 Select as the OLTP engine" },
      { id: "d", label: "CloudFront origin shield for SQL" },
    ],
    answerId: "a",
    explanation: "RDS/Aurora is the managed relational option with backups and Multi-AZ.",
  },
  {
    id: "aws-api-always-on",
    prompt:
      "Node.js API that must stay up continuously (long-lived WebSockets). Least awkward fit?",
    options: [
      { id: "a", label: "EC2 or ECS/Fargate behind a load balancer" },
      { id: "b", label: "Lambda only — ideal for forever-open sockets" },
      { id: "c", label: "S3 static website hosting for the process" },
      { id: "d", label: "Route 53 alone runs the Node runtime" },
    ],
    answerId: "a",
    explanation: "Always-on processes fit EC2/ECS; Lambda is request/event oriented with limits.",
  },
  {
    id: "aws-s3-cloudfront",
    prompt: "Ship a static frontend (HTML/JS/CSS) globally with low latency. Typical combo?",
    options: [
      { id: "a", label: "S3 (origin) + CloudFront (CDN)" },
      { id: "b", label: "Public RDS endpoint for static files" },
      { id: "c", label: "SQS as the web server" },
      { id: "d", label: "IAM users serving files over SSH" },
    ],
    answerId: "a",
    explanation: "Objects in S3, cached at the edge with CloudFront.",
  },
  {
    id: "aws-route53-failover",
    prompt: "DNS failover between primary and secondary regional API endpoints with health checks?",
    options: [
      { id: "a", label: "Amazon Route 53" },
      { id: "b", label: "Amazon SNS" },
      { id: "c", label: "Amazon DynamoDB Streams only" },
      { id: "d", label: "AWS Glue" },
    ],
    answerId: "a",
    explanation: "Route 53 supports failover routing + health checks.",
  },
  {
    id: "aws-elb-asg",
    prompt: "Spread HTTP traffic across EC2 instances and grow/shrink the fleet on CPU. Pattern?",
    options: [
      { id: "a", label: "Elastic Load Balancing + Auto Scaling group" },
      { id: "b", label: "Single Elastic IP updated by cron" },
      { id: "c", label: "S3 Transfer Acceleration for APIs" },
      { id: "d", label: "CloudWatch dashboards alone (no LB)" },
    ],
    answerId: "a",
    explanation: "ALB/NLB distributes traffic; ASG changes capacity from metrics.",
  },
  {
    id: "aws-iam-least-privilege",
    prompt: "CI must upload only to `s3://app-artifacts/*`. Correct approach?",
    options: [
      { id: "a", label: "IAM role/policy scoped to that prefix and needed actions" },
      { id: "b", label: "Root account access keys in the pipeline" },
      { id: "c", label: "AdministratorAccess for every job “just in case”" },
      { id: "d", label: "Disable IAM and use a public writable bucket" },
    ],
    answerId: "a",
    explanation: "Least privilege via IAM roles — never root keys.",
  },
  {
    id: "aws-lambda-apigw",
    prompt: "Spiky webhook traffic (idle most of the day). Prefer pay-per-invocation HTTP?",
    options: [
      { id: "a", label: "API Gateway + Lambda" },
      { id: "b", label: "Always-on EC2 24/7 for ~10 requests/day" },
      { id: "c", label: "RDS Proxy as the public HTTP API" },
      { id: "d", label: "EKS is mandatory for any webhook" },
    ],
    answerId: "a",
    explanation: "Serverless HTTP fits bursty/low traffic well.",
  },
  {
    id: "aws-ecs-vs-eks",
    prompt: "Containers on AWS with less Kubernetes ops overhead?",
    options: [
      { id: "a", label: "Amazon ECS (often with Fargate)" },
      { id: "b", label: "EKS is always lighter ops than ECS" },
      { id: "c", label: "Lambda runs arbitrary Docker Compose files natively" },
      { id: "d", label: "Amplify replaces all container orchestration" },
    ],
    answerId: "a",
    explanation: "ECS is AWS-native orchestration; EKS adds k8s control-plane complexity.",
  },
  {
    id: "aws-dynamodb-kv",
    prompt: "Session store: single-digit ms reads, key-value, massive scale, no SQL joins?",
    options: [
      { id: "a", label: "Amazon DynamoDB" },
      { id: "b", label: "RDS with multi-table JOINs for every session get" },
      { id: "c", label: "Glacier Deep Archive" },
      { id: "d", label: "VPC alone stores sessions" },
    ],
    answerId: "a",
    explanation: "DynamoDB shines at simple key-value access patterns at scale.",
  },
  {
    id: "aws-cloudwatch",
    prompt: "Metrics, logs, and an alarm when 5xx rate > 1% for 5 minutes?",
    options: [
      { id: "a", label: "Amazon CloudWatch" },
      { id: "b", label: "S3 inventory reports only" },
      { id: "c", label: "Route 53 query logs as the only signal" },
      { id: "d", label: "IAM Access Analyzer for HTTP codes" },
    ],
    answerId: "a",
    explanation: "CloudWatch is the default observability hub.",
  },
  {
    id: "aws-sns-fanout",
    prompt: "One fraud event must notify email, SMS, and a Lambda — many subscribers?",
    options: [
      { id: "a", label: "Amazon SNS (pub/sub fan-out)" },
      { id: "b", label: "One SQS queue with a single competing consumer copy" },
      { id: "c", label: "CloudFront invalidation for events" },
      { id: "d", label: "EC2 user-data polling every hour" },
    ],
    answerId: "a",
    explanation: "SNS fans out; SQS is a queue (often SNS→SQS).",
  },
  {
    id: "aws-sqs-decouple",
    prompt: "Checkout must not fail if the email worker is down — buffer and retry jobs?",
    options: [
      { id: "a", label: "Amazon SQS between producer and consumer" },
      { id: "b", label: "Only synchronous Lambda invoke with no buffer" },
      { id: "c", label: "Store jobs in CloudFront cache" },
      { id: "d", label: "Put messages in Route 53 TXT records" },
    ],
    answerId: "a",
    explanation: "SQS decouples with durable buffering and retries.",
  },
  {
    id: "aws-vpc-private-db",
    prompt: "RDS must not be on the public internet; only the app tier can connect.",
    options: [
      {
        id: "a",
        label: "Private subnets + security groups allowing only the app SG (VPC)",
      },
      { id: "b", label: "Bind DB to 0.0.0.0/0 for easier debugging" },
      { id: "c", label: "Put MySQL on CloudFront" },
      { id: "d", label: "Disable VPC networking entirely" },
    ],
    answerId: "a",
    explanation: "Private subnets + SG least privilege is baseline for banks.",
  },
  {
    id: "aws-s3-vs-ebs",
    prompt: "Millions of KYC PDFs via HTTPS URLs — not a disk glued to one VM?",
    options: [
      { id: "a", label: "Amazon S3 object storage" },
      { id: "b", label: "EBS volume on a single EC2" },
      { id: "c", label: "ElastiCache as the document system of record" },
      { id: "d", label: "SQS payloads as the long-term archive" },
    ],
    answerId: "a",
    explanation: "Shared object files at scale → S3. EBS is instance disk.",
  },
  {
    id: "aws-cloudfront-tls",
    prompt: "Terminate TLS close to users and cache GETs for a public marketing site?",
    options: [
      { id: "a", label: "CloudFront distribution in front of the origin" },
      { id: "b", label: "Direct public RDS with SSL" },
      { id: "c", label: "SNS HTTPS subscription as a CDN" },
      { id: "d", label: "IAM Identity Center as CDN" },
    ],
    answerId: "a",
    explanation: "CloudFront is the CDN / TLS edge for HTTP(S).",
  },
  {
    id: "aws-ecs-fargate",
    prompt: "Containerized REST API, no EC2 instance management, always-on behind ALB?",
    options: [
      { id: "a", label: "ECS on Fargate + Application Load Balancer" },
      { id: "b", label: "Lambda zip hosting 30-minute WebSocket servers" },
      { id: "c", label: "S3 + Glacier instant compute" },
      { id: "d", label: "Only bare-metal without containers" },
    ],
    answerId: "a",
    explanation: "Fargate runs containers without managing servers.",
  },
  {
    id: "aws-dynamodb-vs-rds",
    prompt: "Analysts need complex multi-table SQL joins and familiar transactions?",
    options: [
      { id: "a", label: "Amazon RDS / Aurora" },
      { id: "b", label: "DynamoDB single-table for all BI joins" },
      { id: "c", label: "S3 Select as OLTP" },
      { id: "d", label: "CloudWatch Metrics as system of record" },
    ],
    answerId: "a",
    explanation: "Complex SQL/joins fit relational engines.",
  },
  {
    id: "aws-waf-edge",
    prompt: "Block common web exploits (SQLi/XSS patterns) at the edge before the origin?",
    options: [
      { id: "a", label: "AWS WAF on CloudFront or ALB" },
      { id: "b", label: "S3 lifecycle rules" },
      { id: "c", label: "DynamoDB TTL" },
      { id: "d", label: "EBS snapshots" },
    ],
    answerId: "a",
    explanation: "WAF evaluates HTTP requests at supported edges/load balancers.",
  },
  {
    id: "aws-secrets-manager",
    prompt: "Rotate DB credentials automatically; apps fetch secrets at runtime — not hard-coded?",
    options: [
      { id: "a", label: "AWS Secrets Manager (or SSM Parameter Store SecureString)" },
      { id: "b", label: "Commit passwords to the frontend bundle" },
      { id: "c", label: "Store secrets in a public S3 bucket" },
      { id: "d", label: "Put passwords in CloudFront headers" },
    ],
    answerId: "a",
    explanation: "Secrets Manager / SSM are built for secret storage and rotation.",
  },
  {
    id: "aws-multi-az-meaning",
    prompt: "What does Multi-AZ on RDS mainly give you?",
    options: [
      {
        id: "a",
        label: "Synchronous standby in another AZ for failover / higher availability",
      },
      { id: "b", label: "Automatic global CDN for SQL queries" },
      { id: "c", label: "Free unlimited read replicas in every region" },
      { id: "d", label: "Client-side caching in the browser" },
    ],
    answerId: "a",
    explanation: "Multi-AZ = HA standby; read replicas are a separate scaling feature.",
  },
];
