import type { McqQuestion } from "@/domain/exam";

/** MCQ Bank - SQL (banking concepts / queries) */
export const mcqSqlBank: McqQuestion[] = [
  {
    id: "sql-select-basic",
    prompt: "What does `SELECT amount FROM movements WHERE amount > 0` do?",
    options: [
      { id: "a", label: "Deletes positive movements" },
      { id: "b", label: "Returns the amount column from rows with a positive amount" },
      { id: "c", label: "Updates all amounts to 0" },
      { id: "d", label: "Creates an index on amount" },
    ],
    answerId: "b",
    explanation: "SELECT projects columns; WHERE filters rows.",
  },
  {
    id: "sql-join-inner",
    prompt: "An `INNER JOIN` between accounts and movements returns:",
    options: [
      { id: "a", label: "All accounts even if they have no movements" },
      { id: "b", label: "Only rows with a match in both tables" },
      { id: "c", label: "Only rows from the left table" },
      { id: "d", label: "Always a complete Cartesian product" },
    ],
    answerId: "b",
    explanation: "INNER JOIN requires a match in the join condition.",
  },
  {
    id: "sql-left-join",
    prompt: "`LEFT JOIN movements ON ...` from accounts is used to:",
    options: [
      { id: "a", label: "Fetch all accounts and their movements (null if there are none)" },
      { id: "b", label: "Delete accounts without movements" },
      { id: "c", label: "Force only accounts with negative balances" },
      { id: "d", label: "Create a materialized view" },
    ],
    answerId: "a",
    explanation: "LEFT preserves all rows from the left table.",
  },
  {
    id: "sql-group-by",
    prompt: "To total expenses by category, the correct form is:",
    options: [
      { id: "a", label: "SELECT category, SUM(amount) FROM tx GROUP BY category" },
      { id: "b", label: "SELECT category, SUM(amount) FROM tx" },
      { id: "c", label: "SELECT * FROM tx ORDER BY amount" },
      { id: "d", label: "DELETE FROM tx GROUP BY category" },
    ],
    answerId: "a",
    explanation: "Aggregations with non-aggregated columns require GROUP BY.",
  },
  {
    id: "sql-having",
    prompt: "`HAVING` differs from `WHERE` because:",
    options: [
      { id: "a", label: "It filters after grouping (on aggregates)" },
      { id: "b", label: "It only works with DELETE" },
      { id: "c", label: "It is always faster than WHERE" },
      { id: "d", label: "It cannot use COUNT/SUM" },
    ],
    answerId: "a",
    explanation: "WHERE filters rows; HAVING filters groups.",
  },
  {
    id: "sql-index",
    prompt: "An index on `movements(account_id, date)` mainly helps with:",
    options: [
      { id: "a", label: "Queries that filter/order by account and date" },
      { id: "b", label: "Always reducing disk size by half" },
      { id: "c", label: "Avoiding writing INSERT" },
      { id: "d", label: "Replacing the primary key" },
    ],
    answerId: "a",
    explanation: "Composite indexes speed up predicates/order clauses that follow the prefix.",
  },
  {
    id: "sql-pk-unique",
    prompt: "The PRIMARY KEY of a transactions table guarantees:",
    options: [
      { id: "a", label: "Unique, non-null values that identify each row" },
      { id: "b", label: "That amount is always positive" },
      { id: "c", label: "That no foreign keys exist" },
      { id: "d", label: "Automatic alphabetical order" },
    ],
    answerId: "a",
    explanation: "PK = unique identity + NOT NULL.",
  },
  {
    id: "sql-fk",
    prompt: "A FOREIGN KEY from `movements.account_id` to `accounts.id` is used for:",
    options: [
      { id: "a", label: "Referential integrity between movements and accounts" },
      { id: "b", label: "Autocomplete UI in Angular" },
      { id: "c", label: "Encrypting amount" },
      { id: "d", label: "Creating a backup trigger" },
    ],
    answerId: "a",
    explanation: "An FK prevents orphan references (according to ON DELETE/UPDATE rules).",
  },
  {
    id: "sql-null",
    prompt: "In SQL, `amount = NULL` evaluates to:",
    options: [
      { id: "a", label: "TRUE if amount is null" },
      { id: "b", label: "UNKNOWN; use `amount IS NULL`" },
      { id: "c", label: "Always FALSE" },
      { id: "d", label: "A syntax error in all engines" },
    ],
    answerId: "b",
    explanation: "Comparing with NULL does not work with =; use IS NULL.",
  },
  {
    id: "sql-order-limit",
    prompt: "For the 10 most recent movements of an account:",
    options: [
      { id: "a", label: "ORDER BY date DESC LIMIT 10" },
      { id: "b", label: "GROUP BY date LIMIT 10" },
      { id: "c", label: "DISTINCT date ASC" },
      { id: "d", label: "UNION ALL LIMIT 10" },
    ],
    answerId: "a",
    explanation: "Descending order + LIMIT (or FETCH FIRST depending on dialect).",
  },
  {
    id: "sql-distinct",
    prompt: "`SELECT DISTINCT company FROM applications` returns:",
    options: [
      { id: "a", label: "Unique company values" },
      { id: "b", label: "Only the first record in the table" },
      { id: "c", label: "A count of companies" },
      { id: "d", label: "All duplicate rows" },
    ],
    answerId: "a",
    explanation: "DISTINCT removes duplicates from the projected result.",
  },
  {
    id: "sql-transaction",
    prompt: "In a transfer between two accounts, why use a transaction?",
    options: [
      { id: "a", label: "So the debit and credit are confirmed together (atomicity)" },
      { id: "b", label: "To avoid indexes" },
      { id: "c", label: "To disable WHERE" },
      { id: "d", label: "Only for code style" },
    ],
    answerId: "a",
    explanation: "ACID: either both changes are applied or neither is.",
  },
  {
    id: "sql-commit-rollback",
    prompt: "`ROLLBACK` in an open transaction:",
    options: [
      { id: "a", label: "Confirms the changes" },
      { id: "b", label: "Undoes uncommitted changes" },
      { id: "c", label: "Creates a permanent savepoint" },
      { id: "d", label: "Empties the whole database" },
    ],
    answerId: "b",
    explanation: "ROLLBACK reverts; COMMIT confirms.",
  },
  {
    id: "sql-aggregate-count",
    prompt: "`COUNT(*)` vs `COUNT(email)` when email can be NULL:",
    options: [
      { id: "a", label: "COUNT(*) counts rows; COUNT(email) ignores NULL in email" },
      { id: "b", label: "They are always identical" },
      { id: "c", label: "COUNT(email) counts more rows" },
      { id: "d", label: "COUNT(*) does not exist in standard SQL" },
    ],
    answerId: "a",
    explanation: "COUNT(col) does not count NULLs; COUNT(*) does count rows.",
  },
  {
    id: "sql-between",
    prompt: "`amount BETWEEN 100 AND 200` is equivalent to:",
    options: [
      { id: "a", label: "amount >= 100 AND amount <= 200" },
      { id: "b", label: "amount > 100 AND amount < 200" },
      { id: "c", label: "amount = 100 OR amount = 200" },
      { id: "d", label: "amount IN (100)" },
    ],
    answerId: "a",
    explanation: "BETWEEN is inclusive at both ends.",
  },
  {
    id: "sql-like",
    prompt: "To search for descriptions that start with 'PSE' in standard SQL:",
    options: [
      { id: "a", label: "description LIKE 'PSE%'" },
      { id: "b", label: "description = 'PSE*'" },
      { id: "c", label: "description CONTAINS PSE" },
      { id: "d", label: "description REGEX PSE as the only required form" },
    ],
    answerId: "a",
    explanation: "% is the LIKE wildcard for any trailing characters.",
  },
  {
    id: "sql-subquery",
    prompt: "A subquery in `WHERE account_id IN (SELECT id FROM accounts WHERE status='ACTIVE')`:",
    options: [
      { id: "a", label: "Filters movements whose accounts are active" },
      { id: "b", label: "Deletes inactive accounts" },
      { id: "c", label: "Creates an index automatically" },
      { id: "d", label: "Only works with FULL OUTER JOIN" },
    ],
    answerId: "a",
    explanation: "IN receives the set of active ids.",
  },
  {
    id: "sql-view",
    prompt: "A VIEW in SQL is:",
    options: [
      { id: "a", label: "A saved query that is queried like a table" },
      { id: "b", label: "A required physical copy of all data" },
      { id: "c", label: "An audit trigger" },
      { id: "d", label: "A type of hash index" },
    ],
    answerId: "a",
    explanation: "A view is a named query (unless materialized).",
  },
  {
    id: "sql-normalization",
    prompt: "Normalizing tables in a banking core mainly aims to:",
    options: [
      { id: "a", label: "Reduce redundancy and inconsistencies" },
      { id: "b", label: "Duplicate balances in every row" },
      { id: "c", label: "Remove all foreign keys" },
      { id: "d", label: "Store JSON without structure" },
    ],
    answerId: "a",
    explanation: "Normalization organizes dependencies and prevents anomalies.",
  },
  {
    id: "sql-explain",
    prompt: "`EXPLAIN` / execution plan is used to:",
    options: [
      { id: "a", label: "Understand how the engine will access data (indexes, scans)" },
      { id: "b", label: "Run an automatic COMMIT" },
      { id: "c", label: "Create users" },
      { id: "d", label: "Validate CSS" },
    ],
    answerId: "a",
    explanation: "It is used to optimize queries.",
  },
  {
    id: "sql-union",
    prompt: "`UNION` vs `UNION ALL`:",
    options: [
      { id: "a", label: "UNION removes duplicates; UNION ALL keeps them" },
      { id: "b", label: "They are identical" },
      { id: "c", label: "UNION ALL is stricter with types" },
      { id: "d", label: "UNION only works with INSERT" },
    ],
    answerId: "a",
    explanation: "UNION performs an implicit DISTINCT between sets.",
  },
  {
    id: "sql-window",
    prompt: "`SUM(amount) OVER (PARTITION BY account_id ORDER BY date)` calculates:",
    options: [
      { id: "a", label: "A running total by account without collapsing rows" },
      { id: "b", label: "A DELETE by partition" },
      { id: "c", label: "Only the global maximum" },
      { id: "d", label: "A partial index" },
    ],
    answerId: "a",
    explanation: "Window functions aggregate while preserving detail.",
  },
  {
    id: "sql-case",
    prompt: "To label movements as 'credit'/'debit' based on the sign:",
    options: [
      { id: "a", label: "CASE WHEN amount >= 0 THEN 'credit' ELSE 'debit' END" },
      { id: "b", label: "IF amount THEN credit (valid in all pure standard SQL)" },
      { id: "c", label: "SWITCH(amount)" },
      { id: "d", label: "DECODE only in MongoDB" },
    ],
    answerId: "a",
    explanation: "CASE is the portable conditional expression.",
  },
  {
    id: "sql-injection",
    prompt: "To prevent SQL injection in a banking app, you should:",
    options: [
      { id: "a", label: "Use prepared parameters / bind variables" },
      { id: "b", label: "Concatenate user input into the SQL" },
      { id: "c", label: "Disable WHERE" },
      { id: "d", label: "Expose the connection string to the frontend" },
    ],
    answerId: "a",
    explanation: "Prepared statements separate code from data.",
  },
  {
    id: "sql-avg",
    prompt: "`AVG(amount)` over a column with NULLs:",
    options: [
      { id: "a", label: "Ignores NULLs in the average" },
      { id: "b", label: "Always treats NULL as 0" },
      { id: "c", label: "Fails if there is a NULL" },
      { id: "d", label: "Only works with required DISTINCT" },
    ],
    answerId: "a",
    explanation: "Typical numeric aggregates omit NULL.",
  },
  {
    id: "sql-alias",
    prompt: "`SELECT SUM(amount) AS total FROM movements` - `total` is:",
    options: [
      { id: "a", label: "A column alias in the result set" },
      { id: "b", label: "A physical temporary table" },
      { id: "c", label: "A primary key" },
      { id: "d", label: "A stored procedure" },
    ],
    answerId: "a",
    explanation: "AS renames the result column.",
  },
  {
    id: "sql-delete-where",
    prompt: "What risk does `DELETE FROM movements` without WHERE have?",
    options: [
      { id: "a", label: "It can delete all rows in the table" },
      { id: "b", label: "It only deletes the first row" },
      { id: "c", label: "It does nothing" },
      { id: "d", label: "It converts the table into a VIEW" },
    ],
    answerId: "a",
    explanation: "Without WHERE, DELETE applies to the whole table.",
  },
  {
    id: "sql-update",
    prompt: "Updating the status of a specific account requires:",
    options: [
      { id: "a", label: "UPDATE accounts SET status='BLOCKED' WHERE id = ?" },
      { id: "b", label: "UPDATE accounts SET status='BLOCKED'" },
      { id: "c", label: "SELECT status FROM accounts WHERE id = ?" },
      { id: "d", label: "ALTER TABLE accounts BLOCK id" },
    ],
    answerId: "a",
    explanation: "UPDATE + WHERE limits the change.",
  },
  {
    id: "sql-coalesce",
    prompt: "`COALESCE(nickname, full_name, 'Cliente')` returns:",
    options: [
      { id: "a", label: "The first non-NULL value in the list" },
      { id: "b", label: "Always the literal fallback value" },
      { id: "c", label: "The concatenation of all three" },
      { id: "d", label: "An error if nickname is NULL" },
    ],
    answerId: "a",
    explanation: "COALESCE chooses the first non-null value.",
  },
  {
    id: "sql-exists",
    prompt: "`WHERE EXISTS (SELECT 1 FROM movements m WHERE m.account_id = a.id)`:",
    options: [
      { id: "a", label: "Filters accounts that have at least one movement" },
      { id: "b", label: "Counts all movements" },
      { id: "c", label: "Creates the account if it does not exist" },
      { id: "d", label: "Sorts by id" },
    ],
    answerId: "a",
    explanation: "EXISTS stops when it finds the first match.",
  },
];
