import type { McqQuestion } from "@/domain/exam";

/** Banco MCQ Sesión 1 — Fundamentos JS / navegador */
export const mcqFundamentosBank: McqQuestion[] = [
  {
    id: "f-spread-length",
    prompt: "¿Cuál es el resultado de `[...'abc'].length` en JavaScript?",
    options: [
      { id: "a", label: "1" },
      { id: "b", label: "3" },
      { id: "c", label: "undefined" },
      { id: "d", label: "Lanza un TypeError" },
    ],
    answerId: "b",
    explanation: "El spread convierte el string en ['a','b','c'].",
  },
  {
    id: "f-immutability",
    prompt: "En una app bancaria, ¿qué estrategia evita mutar el arreglo de movimientos original?",
    options: [
      { id: "a", label: "Usar .sort() directamente sobre el arreglo" },
      { id: "b", label: "Usar .map() / .filter() y devolver un nuevo arreglo" },
      { id: "c", label: "Asignar propiedades nuevas al mismo objeto" },
      { id: "d", label: "Usar delete sobre índices del arreglo" },
    ],
    answerId: "b",
    explanation: "map/filter producen nuevas colecciones sin mutar la entrada.",
  },
  {
    id: "f-allsettled",
    prompt: "¿Qué hace `Promise.allSettled` frente a `Promise.all`?",
    options: [
      { id: "a", label: "Falla al primer rechazo" },
      { id: "b", label: "Espera todos y reporta fulfilled/rejected por cada promesa" },
      { id: "c", label: "Cancela el resto de promesas" },
      { id: "d", label: "Solo funciona con fetch" },
    ],
    answerId: "b",
    explanation: "allSettled no corta en el primer error.",
  },
  {
    id: "f-virtualization",
    prompt: "Para listar millones de filas en el DOM, la práctica más adecuada es:",
    options: [
      { id: "a", label: "Renderizar todo de una vez" },
      { id: "b", label: "Virtualización / ventanas de render" },
      { id: "c", label: "Usar alert() por fila" },
      { id: "d", label: "Bloquear el hilo principal con un while" },
    ],
    answerId: "b",
    explanation: "La virtualización mantiene el DOM liviano.",
  },
  {
    id: "f-const-let",
    prompt: "¿Cuál es una ventaja de `const` vs `let` al declarar una referencia a un arreglo?",
    options: [
      { id: "a", label: "Congela el contenido del arreglo (Object.freeze)" },
      { id: "b", label: "Impide reasignar la variable a otra referencia" },
      { id: "c", label: "Hace el arreglo inmutable automáticamente" },
      { id: "d", label: "Solo funciona en módulos ESM" },
    ],
    answerId: "b",
    explanation: "const bloquea la reasignación, no la mutación del contenido.",
  },
  {
    id: "f-http-401",
    prompt: "En manejo de errores HTTP, un 401 típicamente indica:",
    options: [
      { id: "a", label: "Recurso no encontrado" },
      { id: "b", label: "No autenticado / token inválido" },
      { id: "c", label: "Error interno del servidor" },
      { id: "d", label: "Conflicto de versión" },
    ],
    answerId: "b",
    explanation: "401 = Unauthorized.",
  },
  {
    id: "f-xss-textcontent",
    prompt: "¿Qué método evita XSS al insertar texto en el DOM?",
    options: [
      { id: "a", label: "element.innerHTML = userInput" },
      { id: "b", label: "element.textContent = userInput" },
      { id: "c", label: "document.write(userInput)" },
      { id: "d", label: "eval(userInput)" },
    ],
    answerId: "b",
    explanation: "textContent trata el valor como texto, no HTML.",
  },
  {
    id: "f-event-loop",
    prompt: "¿Cuál describe mejor el event loop de JavaScript?",
    options: [
      { id: "a", label: "Múltiples hilos de usuario en paralelo" },
      { id: "b", label: "Una cola de tareas + microtareas sobre un solo hilo" },
      { id: "c", label: "Solo macros en Web Workers" },
      { id: "d", label: "Bloqueo síncrono de I/O de red" },
    ],
    answerId: "b",
    explanation: "JS en el navegador es single-threaded con event loop.",
  },
  {
    id: "f-debounce",
    prompt: "Debounce en un buscador de productos sirve para:",
    options: [
      { id: "a", label: "Disparar la búsqueda en cada tecla sin espera" },
      { id: "b", label: "Esperar a que el usuario deje de tipear antes de consultar" },
      { id: "c", label: "Cachear respuestas HTTP eternamente" },
      { id: "d", label: "Cancelar CSS animations" },
    ],
    answerId: "b",
    explanation: "Debounce agrupa eventos rápidos y ejecuta al final de la pausa.",
  },
  {
    id: "f-closure",
    prompt: "Un closure permite:",
    options: [
      { id: "a", label: "Acceder a variables del scope externo aunque la función externa ya terminó" },
      { id: "b", label: "Compilar TypeScript a WebAssembly" },
      { id: "c", label: "Mutar el prototype de Array globalmente de forma segura" },
      { id: "d", label: "Evitar el garbage collector" },
    ],
    answerId: "a",
    explanation: "La función interna conserva referencia al entorno léxico.",
  },
  {
    id: "f-optional-chaining",
    prompt: "`user?.account?.balance` evalúa a undefined si:",
    options: [
      { id: "a", label: "user o account es null/undefined" },
      { id: "b", label: "balance es 0" },
      { id: "c", label: "balance es false" },
      { id: "d", label: "Siempre lanza TypeError" },
    ],
    answerId: "a",
    explanation: "Optional chaining corta en nullish sin lanzar.",
  },
  {
    id: "f-nan",
    prompt: "¿Cuál es la forma correcta de detectar NaN?",
    options: [
      { id: "a", label: "value === NaN" },
      { id: "b", label: "Number.isNaN(value)" },
      { id: "c", label: "value == undefined" },
      { id: "d", label: "typeof value === 'nan'" },
    ],
    answerId: "b",
    explanation: "NaN !== NaN; Number.isNaN es la verificación confiable.",
  },
  {
    id: "f-set-unique",
    prompt: "Para eliminar duplicados de un arreglo de IDs string, lo más idiomático es:",
    options: [
      { id: "a", label: "[...new Set(ids)]" },
      { id: "b", label: "ids.sort()" },
      { id: "c", label: "ids.reverse()" },
      { id: "d", label: "ids.splice(0)" },
    ],
    answerId: "a",
    explanation: "Set guarda valores únicos; el spread lo vuelve arreglo.",
  },
  {
    id: "f-microtask",
    prompt: "Una Promise.resolve().then(...) se encola como:",
    options: [
      { id: "a", label: "Macrotarea (setTimeout)" },
      { id: "b", label: "Microtarea" },
      { id: "c", label: "Tarea de CSS" },
      { id: "d", label: "Worker thread obligatorio" },
    ],
    answerId: "b",
    explanation: "Los then de promesas van a la cola de microtareas.",
  },
  {
    id: "f-strict-equality",
    prompt: "`0 == '0'` y `0 === '0'` evalúan respectivamente a:",
    options: [
      { id: "a", label: "true y true" },
      { id: "b", label: "true y false" },
      { id: "c", label: "false y true" },
      { id: "d", label: "false y false" },
    ],
    answerId: "b",
    explanation: "== hace coerción; === no.",
  },
  {
    id: "f-fetch-abort",
    prompt: "Para cancelar un fetch en curso se usa típicamente:",
    options: [
      { id: "a", label: "AbortController + signal" },
      { id: "b", label: "fetch.cancel()" },
      { id: "c", label: "window.stopFetch()" },
      { id: "d", label: "JSON.parse(null)" },
    ],
    answerId: "a",
    explanation: "AbortController permite abortar la request asociada.",
  },
  {
    id: "f-map-vs-object",
    prompt: "Una ventaja de `Map` frente a un Object plano como diccionario es:",
    options: [
      { id: "a", label: "Las claves pueden ser de cualquier tipo y .size es confiable" },
      { id: "b", label: "No puede iterarse" },
      { id: "c", label: "Solo admite claves number" },
      { id: "d", label: "Es más lento siempre por definición" },
    ],
    answerId: "a",
    explanation: "Map preserva orden de inserción y no hereda keys del prototype.",
  },
  {
    id: "f-pure-function",
    prompt: "Una función pura:",
    options: [
      { id: "a", label: "Depende solo de sus argumentos y no produce side effects" },
      { id: "b", label: "Siempre escribe en localStorage" },
      { id: "c", label: "Debe usar this del componente" },
      { id: "d", label: "Solo puede retornar void" },
    ],
    answerId: "a",
    explanation: "Misma entrada → misma salida, sin efectos colaterales.",
  },
  {
    id: "f-json-clone",
    prompt: "¿Cuál es un riesgo de clonar con `JSON.parse(JSON.stringify(obj))`?",
    options: [
      { id: "a", label: "Pierde Date, undefined, funciones y Map/Set" },
      { id: "b", label: "Es la única forma de clonar en JS" },
      { id: "c", label: "Congela el objeto resultante" },
      { id: "d", label: "Solo funciona en Node.js" },
    ],
    answerId: "a",
    explanation: "La serialización JSON no preserva tipos complejos.",
  },
  {
    id: "f-nullish",
    prompt: "`value ?? 'N/A'` usa el fallback cuando value es:",
    options: [
      { id: "a", label: "0 o ''" },
      { id: "b", label: "null o undefined" },
      { id: "c", label: "false" },
      { id: "d", label: "Cualquier falsy" },
    ],
    answerId: "b",
    explanation: "?? solo reacciona a nullish, no a todos los falsy.",
  },
  {
    id: "f-array-reduce",
    prompt: "Para calcular el total de un carrito, lo más expresivo suele ser:",
    options: [
      { id: "a", label: "items.reduce((sum, i) => sum + i.price * i.qty, 0)" },
      { id: "b", label: "items.forEach sin acumular" },
      { id: "c", label: "items.pop() en loop" },
      { id: "d", label: "items.splice(0, items.length)" },
    ],
    answerId: "a",
    explanation: "reduce acumula un valor a partir de la colección.",
  },
  {
    id: "f-tdz",
    prompt: "Acceder a una `let` antes de su declaración produce:",
    options: [
      { id: "a", label: "undefined silenciosamente" },
      { id: "b", label: "ReferenceError (temporal dead zone)" },
      { id: "c", label: "null" },
      { id: "d", label: "0" },
    ],
    answerId: "b",
    explanation: "let/const están en TDZ hasta la inicialización.",
  },
  {
    id: "f-module-export",
    prompt: "En ESM, `export default` permite:",
    options: [
      { id: "a", label: "Un valor principal por módulo, importable con cualquier nombre" },
      { id: "b", label: "Solo exportar strings" },
      { id: "c", label: "Evitar tree-shaking siempre" },
      { id: "d", label: "Reemplazar import dinámico" },
    ],
    answerId: "a",
    explanation: "Default export es el export principal del módulo.",
  },
  {
    id: "f-cors",
    prompt: "Un error CORS en el navegador indica principalmente que:",
    options: [
      { id: "a", label: "El servidor no autorizó el origen de la página" },
      { id: "b", label: "JSON está mal formado" },
      { id: "c", label: "CSS no cargó" },
      { id: "d", label: "TypeScript no compiló" },
    ],
    answerId: "a",
    explanation: "CORS es una política del navegador basada en headers del servidor.",
  },
];
