import type { McqQuestion } from "@/domain/exam";

export const mcqEngineeringBank: McqQuestion[] = [
  {
    id: "eng-clean-naming-intent",
    prompt: "Which variable name best follows Clean Code guidance for a frontend payment summary?",
    options: [
      { id: "a", label: "x" },
      { id: "b", label: "data2" },
      { id: "c", label: "totalApprovedAmount" },
      { id: "d", label: "thing" },
    ],
    answerId: "c",
    explanation: "A good name reveals intent and domain meaning without requiring extra comments.",
  },
  {
    id: "eng-clean-function-size",
    prompt: "A component method validates a form, maps a request, calls HTTP, updates state, logs analytics, and formats errors. What is the main Clean Code issue?",
    options: [
      { id: "a", label: "The method probably has too many responsibilities" },
      { id: "b", label: "The method should always be made static" },
      { id: "c", label: "The method has too few comments" },
      { id: "d", label: "The method should use more nested conditions" },
    ],
    answerId: "a",
    explanation: "Small functions should do one thing at one level of abstraction.",
  },
  {
    id: "eng-clean-comments-why",
    prompt: "Which comment is most useful in clean code?",
    options: [
      { id: "a", label: "A comment that repeats the next line of code" },
      { id: "b", label: "A comment explaining a non-obvious business rule or trade-off" },
      { id: "c", label: "A comment for every variable assignment" },
      { id: "d", label: "A comment that hides dead code for later" },
    ],
    answerId: "b",
    explanation: "Useful comments explain why something is necessary when the code cannot express it clearly enough.",
  },
  {
    id: "eng-clean-boy-scout-rule",
    prompt: "What does the Boy Scout Rule mean in software maintenance?",
    options: [
      { id: "a", label: "Only refactor code during dedicated cleanup sprints" },
      { id: "b", label: "Leave the code a little cleaner than you found it" },
      { id: "c", label: "Rewrite every file you touch" },
      { id: "d", label: "Avoid changing code unless there is a production incident" },
    ],
    answerId: "b",
    explanation: "The rule encourages small, safe improvements while working in an area of the codebase.",
  },
  {
    id: "eng-clean-dry-kiss-yagni",
    prompt: "A developer builds a complex plugin framework for a screen that has only one known variant. Which principle warns against this?",
    options: [
      { id: "a", label: "YAGNI" },
      { id: "b", label: "DRY" },
      { id: "c", label: "Observer" },
      { id: "d", label: "AAA" },
    ],
    answerId: "a",
    explanation: "YAGNI means do not build functionality until there is a real need for it.",
  },
  {
    id: "eng-solid-srp-component",
    prompt: "Which example best follows the Single Responsibility Principle in a frontend feature?",
    options: [
      { id: "a", label: "A component that renders UI, builds SQL, sends emails, and stores tokens" },
      { id: "b", label: "A component that delegates pricing calculation to a domain service" },
      { id: "c", label: "A service that handles every use case in the application" },
      { id: "d", label: "A utility file named helpers.ts with unrelated functions" },
    ],
    answerId: "b",
    explanation: "SRP keeps each module focused on one reason to change.",
  },
  {
    id: "eng-solid-ocp-pricing",
    prompt: "A discount calculator needs new campaign types often. Which design best supports the Open/Closed Principle?",
    options: [
      { id: "a", label: "Add a new if block to a long function for every campaign" },
      { id: "b", label: "Use interchangeable discount strategies behind a stable interface" },
      { id: "c", label: "Copy the full calculator for each campaign" },
      { id: "d", label: "Hard-code campaign names in the component template" },
    ],
    answerId: "b",
    explanation: "OCP favors extending behavior through new implementations without modifying stable code repeatedly.",
  },
  {
    id: "eng-solid-lsp-substitution",
    prompt: "Which situation violates the Liskov Substitution Principle?",
    options: [
      { id: "a", label: "A mock repository returns the same kind of data as the real repository" },
      { id: "b", label: "A subclass throws errors for methods that the base type promises to support" },
      { id: "c", label: "A function receives an interface instead of a concrete class" },
      { id: "d", label: "A component receives input data through props" },
    ],
    answerId: "b",
    explanation: "LSP requires derived implementations to be safely usable wherever the base contract is expected.",
  },
  {
    id: "eng-solid-isp-fat-interface",
    prompt: "Which design follows the Interface Segregation Principle?",
    options: [
      { id: "a", label: "A small ReadAccountsPort used by a screen that only lists accounts" },
      { id: "b", label: "A huge BankingService interface with 80 methods required by every component" },
      { id: "c", label: "A component importing every repository in the app" },
      { id: "d", label: "One DTO type reused for unrelated forms" },
    ],
    answerId: "a",
    explanation: "ISP says clients should not depend on methods they do not use.",
  },
  {
    id: "eng-solid-dip-frontend",
    prompt: "In a frontend Clean Architecture design, what best demonstrates the Dependency Inversion Principle?",
    options: [
      { id: "a", label: "The domain use case depends directly on window.fetch" },
      { id: "b", label: "The UI imports an Axios instance and builds every URL" },
      { id: "c", label: "A use case depends on a repository interface implemented by infrastructure" },
      { id: "d", label: "All modules depend on a global singleton object" },
    ],
    answerId: "c",
    explanation: "DIP makes high-level policy depend on abstractions, not concrete infrastructure details.",
  },
  {
    id: "eng-solid-common-god-component",
    prompt: "A 900-line component owns routing decisions, API calls, validation, formatting, and business rules. Which violation is most likely?",
    options: [
      { id: "a", label: "Single Responsibility Principle violation" },
      { id: "b", label: "Liskov Substitution Principle violation only" },
      { id: "c", label: "No violation because components may contain any logic" },
      { id: "d", label: "Decorator pattern violation" },
    ],
    answerId: "a",
    explanation: "A god component usually has many reasons to change and is difficult to test or maintain.",
  },
  {
    id: "eng-solid-common-switch-violation",
    prompt: "A payment component has a large switch that changes behavior for every payment provider and is edited for each new provider. What is the main design smell?",
    options: [
      { id: "a", label: "It is closed for extension and open for modification" },
      { id: "b", label: "It uses too few primitive types" },
      { id: "c", label: "It has too many unit tests" },
      { id: "d", label: "It avoids all abstractions" },
    ],
    answerId: "a",
    explanation: "Repeated edits to add variants suggest an Open/Closed Principle problem.",
  },
  {
    id: "eng-pattern-factory-creation",
    prompt: "When is a Factory pattern useful in frontend code?",
    options: [
      { id: "a", label: "When object creation depends on runtime configuration or environment" },
      { id: "b", label: "When every class must be global" },
      { id: "c", label: "When all validation should be removed" },
      { id: "d", label: "When a component should know every constructor detail" },
    ],
    answerId: "a",
    explanation: "A factory centralizes creation decisions, such as choosing a mock, REST, or local-storage adapter.",
  },
  {
    id: "eng-pattern-strategy-validation",
    prompt: "A form supports different validation rules for savings, credit card, and loan products. Which GoF pattern is a good fit?",
    options: [
      { id: "a", label: "Strategy" },
      { id: "b", label: "Singleton" },
      { id: "c", label: "Facade" },
      { id: "d", label: "Observer" },
    ],
    answerId: "a",
    explanation: "Strategy lets the app swap algorithms behind a common interface.",
  },
  {
    id: "eng-pattern-observer-state",
    prompt: "The Observer pattern is most closely related to which frontend behavior?",
    options: [
      { id: "a", label: "Subscribers reacting when state or events change" },
      { id: "b", label: "Compiling TypeScript types at runtime" },
      { id: "c", label: "Encrypting all CSS files" },
      { id: "d", label: "Creating only one object in the whole app" },
    ],
    answerId: "a",
    explanation: "Observer models one-to-many notification, common in event emitters and reactive streams.",
  },
  {
    id: "eng-pattern-adapter-api",
    prompt: "A backend returns `{ acct_no, bal }`, but the UI expects `{ accountNumber, balance }`. Which pattern helps isolate this mismatch?",
    options: [
      { id: "a", label: "Adapter" },
      { id: "b", label: "Singleton" },
      { id: "c", label: "Observer" },
      { id: "d", label: "Command" },
    ],
    answerId: "a",
    explanation: "An adapter converts one interface or data shape into another expected by the client.",
  },
  {
    id: "eng-pattern-decorator-crosscutting",
    prompt: "Which frontend example best matches the Decorator pattern?",
    options: [
      { id: "a", label: "Wrapping a repository with caching while keeping the same interface" },
      { id: "b", label: "Renaming all files to index.ts" },
      { id: "c", label: "Replacing all services with one global variable" },
      { id: "d", label: "Putting every feature into one component" },
    ],
    answerId: "a",
    explanation: "Decorator adds behavior around an object without changing its public contract.",
  },
  {
    id: "eng-pattern-singleton-pitfall",
    prompt: "What is a common pitfall of using Singleton-like global services in frontend applications?",
    options: [
      { id: "a", label: "They can hide shared mutable state and make tests order-dependent" },
      { id: "b", label: "They always improve isolation" },
      { id: "c", label: "They prevent memory leaks automatically" },
      { id: "d", label: "They remove the need for dependency boundaries" },
    ],
    answerId: "a",
    explanation: "Global state can couple tests and features unless lifetime and dependencies are controlled carefully.",
  },
  {
    id: "eng-pattern-facade-http",
    prompt: "Why might a frontend team create an AccountFacade for account screens?",
    options: [
      { id: "a", label: "To expose a simple API over use cases, state, and data loading details" },
      { id: "b", label: "To force components to know all HTTP headers" },
      { id: "c", label: "To make every method private" },
      { id: "d", label: "To bypass domain rules" },
    ],
    answerId: "a",
    explanation: "A facade provides a simpler interface to a more complex subsystem.",
  },
  {
    id: "eng-architecture-layering",
    prompt: "In Clean Architecture for frontend, which responsibility belongs primarily in the Domain layer?",
    options: [
      { id: "a", label: "Rendering CSS classes" },
      { id: "b", label: "HTTP retry configuration" },
      { id: "c", label: "Business rules and use cases" },
      { id: "d", label: "Browser localStorage serialization details" },
    ],
    answerId: "c",
    explanation: "The domain layer holds business concepts and application rules independent of UI and infrastructure.",
  },
  {
    id: "eng-architecture-dependency-rule",
    prompt: "What does the Clean Architecture dependency rule require?",
    options: [
      { id: "a", label: "Inner layers should not depend on outer layers" },
      { id: "b", label: "The UI layer should own all domain entities" },
      { id: "c", label: "Infrastructure code must be imported by every use case directly" },
      { id: "d", label: "CSS files should import repositories" },
    ],
    answerId: "a",
    explanation: "Dependencies point inward: domain policies stay independent from UI frameworks and infrastructure.",
  },
  {
    id: "eng-architecture-ui-http-details",
    prompt: "Why should a UI component avoid knowing low-level HTTP details such as URLs, headers, and response DTO quirks?",
    options: [
      { id: "a", label: "It keeps UI focused on presentation and reduces coupling to infrastructure" },
      { id: "b", label: "It makes API calls impossible" },
      { id: "c", label: "It removes the need for error handling" },
      { id: "d", label: "It guarantees perfect performance" },
    ],
    answerId: "a",
    explanation: "Keeping HTTP details behind adapters or repositories makes UI easier to test and change.",
  },
  {
    id: "eng-architecture-infrastructure-adapters",
    prompt: "In a layered frontend app, where should mapping from remote API DTOs to domain models usually live?",
    options: [
      { id: "a", label: "In the infrastructure adapter or repository implementation" },
      { id: "b", label: "Inside every template expression" },
      { id: "c", label: "Only in CSS" },
      { id: "d", label: "In the test runner configuration" },
    ],
    answerId: "a",
    explanation: "Infrastructure adapters isolate external formats from the rest of the application.",
  },
  {
    id: "eng-testing-what-to-test",
    prompt: "What should a unit test for a transfer amount validator focus on?",
    options: [
      { id: "a", label: "Observable behavior for valid and invalid amounts" },
      { id: "b", label: "The exact private variable names used internally" },
      { id: "c", label: "The color of the submit button" },
      { id: "d", label: "The order of unrelated imports" },
    ],
    answerId: "a",
    explanation: "Unit tests should verify behavior and important edge cases, not incidental implementation details.",
  },
  {
    id: "eng-testing-aaa-structure",
    prompt: "What does the AAA pattern in unit testing stand for?",
    options: [
      { id: "a", label: "Arrange, Act, Assert" },
      { id: "b", label: "Authorize, Audit, Archive" },
      { id: "c", label: "Adapt, Aggregate, Animate" },
      { id: "d", label: "Analyze, Allocate, Apply" },
    ],
    answerId: "a",
    explanation: "AAA keeps tests readable by separating setup, execution, and verification.",
  },
  {
    id: "eng-testing-mocks-vs-stubs",
    prompt: "What is a practical difference between a stub and a mock?",
    options: [
      { id: "a", label: "A stub provides controlled data; a mock can also verify interactions" },
      { id: "b", label: "A stub is only used in production" },
      { id: "c", label: "A mock can never fail a test" },
      { id: "d", label: "They are browser storage APIs" },
    ],
    answerId: "a",
    explanation: "Stubs help drive test inputs, while mocks often include expectations about calls.",
  },
  {
    id: "eng-testing-pure-functions",
    prompt: "Why are pure functions usually easy to unit test?",
    options: [
      { id: "a", label: "The same input always produces the same output without hidden side effects" },
      { id: "b", label: "They require a real backend to execute" },
      { id: "c", label: "They depend on the current clock by default" },
      { id: "d", label: "They mutate global state automatically" },
    ],
    answerId: "a",
    explanation: "Deterministic behavior and no side effects make tests simpler and more reliable.",
  },
  {
    id: "eng-testing-avoid-implementation",
    prompt: "Which test is most likely too coupled to implementation details?",
    options: [
      { id: "a", label: "It checks that a user sees an error when the transfer limit is exceeded" },
      { id: "b", label: "It checks that a private helper is called exactly three times" },
      { id: "c", label: "It checks that a validator rejects negative amounts" },
      { id: "d", label: "It checks that a repository receives the expected command" },
    ],
    answerId: "b",
    explanation: "Tests coupled to private internals often break during safe refactors without behavior changes.",
  },
  {
    id: "eng-sonarqube-code-smells",
    prompt: "In SonarQube, what is a code smell?",
    options: [
      { id: "a", label: "A maintainability issue that may make code harder to understand or change" },
      { id: "b", label: "A guaranteed runtime crash" },
      { id: "c", label: "A CSS-only browser warning" },
      { id: "d", label: "A dependency downloaded from npm" },
    ],
    answerId: "a",
    explanation: "Code smells are maintainability findings, such as duplicated code or overly complex functions.",
  },
  {
    id: "eng-sonarqube-coverage-gate",
    prompt: "What is the purpose of a SonarQube quality gate with coverage requirements?",
    options: [
      { id: "a", label: "To define measurable conditions that code must satisfy before being accepted" },
      { id: "b", label: "To replace all code review" },
      { id: "c", label: "To prove the application has no bugs" },
      { id: "d", label: "To disable unit tests in CI" },
    ],
    answerId: "a",
    explanation: "A quality gate gives teams objective thresholds, but it does not replace engineering judgment.",
  },
  {
    id: "eng-sonarqube-cognitive-complexity",
    prompt: "What does high cognitive complexity usually indicate?",
    options: [
      { id: "a", label: "The code has control flow that is hard for humans to follow" },
      { id: "b", label: "The code has too much test coverage" },
      { id: "c", label: "The code uses too many CSS variables" },
      { id: "d", label: "The code has no dependencies" },
    ],
    answerId: "a",
    explanation: "Nested branching and tangled flow increase cognitive complexity and maintenance risk.",
  },
  {
    id: "eng-sonarqube-fix-blockers",
    prompt: "Why should blocker or critical findings in SonarQube be fixed before merging?",
    options: [
      { id: "a", label: "They may represent serious reliability, security, or maintainability risks" },
      { id: "b", label: "They are only formatting opinions" },
      { id: "c", label: "They always mean the CI server is broken" },
      { id: "d", label: "They are safe to ignore if the UI looks correct" },
    ],
    answerId: "a",
    explanation: "High-severity findings deserve attention because they often signal real production risk.",
  },
  {
    id: "eng-appsec-xss-output-encoding",
    prompt: "Which frontend practice helps prevent reflected or stored XSS?",
    options: [
      { id: "a", label: "Render untrusted user input with innerHTML by default" },
      { id: "b", label: "Use safe templating, output encoding, and sanitization when HTML is unavoidable" },
      { id: "c", label: "Disable linting in production builds" },
      { id: "d", label: "Store user input in a global variable before rendering it" },
    ],
    answerId: "b",
    explanation: "Treat untrusted input as data, not executable markup; sanitize only when rich HTML is truly needed.",
  },
  {
    id: "eng-appsec-secrets-client",
    prompt: "Why should API secrets not be stored in frontend source code or browser bundles?",
    options: [
      { id: "a", label: "Anything shipped to the browser can be inspected by users or attackers" },
      { id: "b", label: "TypeScript cannot compile strings" },
      { id: "c", label: "Secrets make CSS slower" },
      { id: "d", label: "Browsers automatically rotate secrets every day" },
    ],
    answerId: "a",
    explanation: "Client-side code is not a safe secret store; sensitive credentials belong on trusted servers or managed platforms.",
  },
  {
    id: "eng-appsec-dependency-scanning",
    prompt: "What is the most practical mindset for frontend dependency security?",
    options: [
      { id: "a", label: "Install packages freely and never update them" },
      { id: "b", label: "Use dependency scanning, review risk, and update or replace vulnerable packages" },
      { id: "c", label: "Assume npm packages are safe because they are public" },
      { id: "d", label: "Copy minified code into the repository to avoid audits" },
    ],
    answerId: "b",
    explanation: "Dependency scanning is part of ongoing risk management, not a one-time checklist.",
  },
  {
    id: "eng-appsec-fluid-attacks-sdlc",
    prompt: "How does Fluid Attacks relate to a secure SDLC?",
    options: [
      { id: "a", label: "It is a security company focused on continuous hacking and AppSec practices" },
      { id: "b", label: "It is a CSS framework for banking dashboards" },
      { id: "c", label: "It replaces all developer testing with screenshots" },
      { id: "d", label: "It is a browser API for encrypting localStorage" },
    ],
    answerId: "a",
    explanation: "Fluid Attacks focuses on finding and helping remediate security weaknesses continuously across the software lifecycle.",
  },
];
