import type { McqQuestion } from "@/domain/exam";

/** MCQ bank Session 1 — JS / browser fundamentals */
export const mcqFundamentosBank: McqQuestion[] = [
  {
    id: "f-spread-length",
    prompt: "What is the result of `[...'abc'].length` in JavaScript?",
    options: [
      { id: "a", label: "1" },
      { id: "b", label: "3" },
      { id: "c", label: "undefined" },
      { id: "d", label: "It throws a TypeError" },
    ],
    answerId: "b",
    explanation: "The spread operator converts the string into ['a','b','c'].",
  },
  {
    id: "f-immutability",
    prompt: "In a banking app, which strategy avoids mutating the original movements array?",
    options: [
      { id: "a", label: "Use .sort() directly on the array" },
      { id: "b", label: "Use .map() / .filter() and return a new array" },
      { id: "c", label: "Assign new properties to the same object" },
      { id: "d", label: "Use delete on array indexes" },
    ],
    answerId: "b",
    explanation: "map/filter produce new collections without mutating the input.",
  },
  {
    id: "f-allsettled",
    prompt: "What does `Promise.allSettled` do compared with `Promise.all`?",
    options: [
      { id: "a", label: "Fails on the first rejection" },
      { id: "b", label: "Waits for all and reports fulfilled/rejected for each promise" },
      { id: "c", label: "Cancels the remaining promises" },
      { id: "d", label: "Only works with fetch" },
    ],
    answerId: "b",
    explanation: "allSettled does not stop at the first error.",
  },
  {
    id: "f-virtualization",
    prompt: "To list millions of rows in the DOM, the most appropriate practice is:",
    options: [
      { id: "a", label: "Render everything at once" },
      { id: "b", label: "Virtualization / render windows" },
      { id: "c", label: "Use alert() for each row" },
      { id: "d", label: "Block the main thread with a while" },
    ],
    answerId: "b",
    explanation: "Virtualization keeps the DOM lightweight.",
  },
  {
    id: "f-const-let",
    prompt: "What is one advantage of `const` vs `let` when declaring a reference to an array?",
    options: [
      { id: "a", label: "Freezes the array contents (Object.freeze)" },
      { id: "b", label: "Prevents reassigning the variable to another reference" },
      { id: "c", label: "Makes the array immutable automatically" },
      { id: "d", label: "Only works in ESM modules" },
    ],
    answerId: "b",
    explanation: "const blocks reassignment, not mutation of the contents.",
  },
  {
    id: "f-http-401",
    prompt: "In HTTP error handling, a 401 typically indicates:",
    options: [
      { id: "a", label: "Resource not found" },
      { id: "b", label: "Not authenticated / invalid token" },
      { id: "c", label: "Internal server error" },
      { id: "d", label: "Version conflict" },
    ],
    answerId: "b",
    explanation: "401 = Unauthorized.",
  },
  {
    id: "f-xss-textcontent",
    prompt: "Which method prevents XSS when inserting text into the DOM?",
    options: [
      { id: "a", label: "element.innerHTML = userInput" },
      { id: "b", label: "element.textContent = userInput" },
      { id: "c", label: "document.write(userInput)" },
      { id: "d", label: "eval(userInput)" },
    ],
    answerId: "b",
    explanation: "textContent treats the value as text, not HTML.",
  },
  {
    id: "f-event-loop",
    prompt: "Which best describes the JavaScript event loop?",
    options: [
      { id: "a", label: "Multiple user threads running in parallel" },
      { id: "b", label: "A task queue + microtasks on a single thread" },
      { id: "c", label: "Only macros in Web Workers" },
      { id: "d", label: "Synchronous blocking of network I/O" },
    ],
    answerId: "b",
    explanation: "JS in the browser is single-threaded with an event loop.",
  },
  {
    id: "f-debounce",
    prompt: "Debounce in a product search field is used to:",
    options: [
      { id: "a", label: "Trigger the search on every keystroke without waiting" },
      { id: "b", label: "Wait until the user stops typing before querying" },
      { id: "c", label: "Cache HTTP responses forever" },
      { id: "d", label: "Cancel CSS animations" },
    ],
    answerId: "b",
    explanation: "Debounce groups rapid events and runs at the end of the pause.",
  },
  {
    id: "f-closure",
    prompt: "A closure allows you to:",
    options: [
      { id: "a", label: "Access variables from the outer scope even after the outer function has finished" },
      { id: "b", label: "Compile TypeScript to WebAssembly" },
      { id: "c", label: "Safely mutate the Array prototype globally" },
      { id: "d", label: "Avoid the garbage collector" },
    ],
    answerId: "a",
    explanation: "The inner function keeps a reference to the lexical environment.",
  },
  {
    id: "f-optional-chaining",
    prompt: "`user?.account?.balance` evaluates to undefined if:",
    options: [
      { id: "a", label: "user or account is null/undefined" },
      { id: "b", label: "balance is 0" },
      { id: "c", label: "balance is false" },
      { id: "d", label: "It always throws TypeError" },
    ],
    answerId: "a",
    explanation: "Optional chaining short-circuits on nullish values without throwing.",
  },
  {
    id: "f-nan",
    prompt: "What is the correct way to detect NaN?",
    options: [
      { id: "a", label: "value === NaN" },
      { id: "b", label: "Number.isNaN(value)" },
      { id: "c", label: "value == undefined" },
      { id: "d", label: "typeof value === 'nan'" },
    ],
    answerId: "b",
    explanation: "NaN !== NaN; Number.isNaN is the reliable check.",
  },
  {
    id: "f-set-unique",
    prompt: "To remove duplicates from an array of string IDs, the most idiomatic approach is:",
    options: [
      { id: "a", label: "[...new Set(ids)]" },
      { id: "b", label: "ids.sort()" },
      { id: "c", label: "ids.reverse()" },
      { id: "d", label: "ids.splice(0)" },
    ],
    answerId: "a",
    explanation: "Set stores unique values; the spread turns it back into an array.",
  },
  {
    id: "f-microtask",
    prompt: "A Promise.resolve().then(...) is queued as:",
    options: [
      { id: "a", label: "Macrotask (setTimeout)" },
      { id: "b", label: "Microtask" },
      { id: "c", label: "CSS task" },
      { id: "d", label: "Mandatory Worker thread" },
    ],
    answerId: "b",
    explanation: "Promise then callbacks go to the microtask queue.",
  },
  {
    id: "f-strict-equality",
    prompt: "`0 == '0'` and `0 === '0'` evaluate respectively to:",
    options: [
      { id: "a", label: "true and true" },
      { id: "b", label: "true and false" },
      { id: "c", label: "false and true" },
      { id: "d", label: "false and false" },
    ],
    answerId: "b",
    explanation: "== performs coercion; === does not.",
  },
  {
    id: "f-fetch-abort",
    prompt: "To cancel an in-progress fetch, you typically use:",
    options: [
      { id: "a", label: "AbortController + signal" },
      { id: "b", label: "fetch.cancel()" },
      { id: "c", label: "window.stopFetch()" },
      { id: "d", label: "JSON.parse(null)" },
    ],
    answerId: "a",
    explanation: "AbortController lets you abort the associated request.",
  },
  {
    id: "f-map-vs-object",
    prompt: "One advantage of `Map` over a plain Object as a dictionary is:",
    options: [
      { id: "a", label: "Keys can be of any type and .size is reliable" },
      { id: "b", label: "It cannot be iterated" },
      { id: "c", label: "It only accepts number keys" },
      { id: "d", label: "It is always slower by definition" },
    ],
    answerId: "a",
    explanation: "Map preserves insertion order and does not inherit keys from the prototype.",
  },
  {
    id: "f-pure-function",
    prompt: "A pure function:",
    options: [
      { id: "a", label: "Depends only on its arguments and produces no side effects" },
      { id: "b", label: "Always writes to localStorage" },
      { id: "c", label: "Must use the component's this" },
      { id: "d", label: "Can only return void" },
    ],
    answerId: "a",
    explanation: "Same input -> same output, with no side effects.",
  },
  {
    id: "f-json-clone",
    prompt: "What is one risk of cloning with `JSON.parse(JSON.stringify(obj))`?",
    options: [
      { id: "a", label: "It loses Date, undefined, functions, and Map/Set" },
      { id: "b", label: "It is the only way to clone in JS" },
      { id: "c", label: "It freezes the resulting object" },
      { id: "d", label: "It only works in Node.js" },
    ],
    answerId: "a",
    explanation: "JSON serialization does not preserve complex types.",
  },
  {
    id: "f-nullish",
    prompt: "`value ?? 'N/A'` uses the fallback when value is:",
    options: [
      { id: "a", label: "0 or ''" },
      { id: "b", label: "null or undefined" },
      { id: "c", label: "false" },
      { id: "d", label: "Any falsy value" },
    ],
    answerId: "b",
    explanation: "?? only reacts to nullish values, not all falsy values.",
  },
  {
    id: "f-array-reduce",
    prompt: "To calculate the total of a cart, the most expressive option is usually:",
    options: [
      { id: "a", label: "items.reduce((sum, i) => sum + i.price * i.qty, 0)" },
      { id: "b", label: "items.forEach without accumulating" },
      { id: "c", label: "items.pop() in a loop" },
      { id: "d", label: "items.splice(0, items.length)" },
    ],
    answerId: "a",
    explanation: "reduce accumulates a value from the collection.",
  },
  {
    id: "f-tdz",
    prompt: "Accessing a `let` before its declaration produces:",
    options: [
      { id: "a", label: "undefined silently" },
      { id: "b", label: "ReferenceError (temporal dead zone)" },
      { id: "c", label: "null" },
      { id: "d", label: "0" },
    ],
    answerId: "b",
    explanation: "let/const are in the TDZ until initialization.",
  },
  {
    id: "f-module-export",
    prompt: "In ESM, `export default` allows:",
    options: [
      { id: "a", label: "One main value per module, importable with any name" },
      { id: "b", label: "Only exporting strings" },
      { id: "c", label: "Always avoiding tree-shaking" },
      { id: "d", label: "Replacing dynamic import" },
    ],
    answerId: "a",
    explanation: "Default export is the module's main export.",
  },
  {
    id: "f-cors",
    prompt: "A CORS error in the browser mainly indicates that:",
    options: [
      { id: "a", label: "The server did not authorize the page's origin" },
      { id: "b", label: "JSON is malformed" },
      { id: "c", label: "CSS did not load" },
      { id: "d", label: "TypeScript did not compile" },
    ],
    answerId: "a",
    explanation: "CORS is a browser policy based on server headers.",
  },
];
