import type { McqQuestion } from "@/domain/exam";

/** Lean JS: code-result + map/filter/reduce (Bancolombia MCQ). */
export const mcqJsEssentialsBank: McqQuestion[] = [
  {
    id: "f-spread-length",
    prompt: "What is the result of `[...'abc'].length` in JavaScript?",
    options: [
      { id: "a", label: "1" },
      { id: "b", label: "3" },
      { id: "c", label: "undefined" },
      { id: "d", label: "It throws a TypeError" },
    ],
    answerId: "b",
    explanation: "The spread operator converts the string into ['a','b','c'].",
  },
  {
    id: "f-immutability",
    prompt: "In a banking app, which strategy avoids mutating the original movements array?",
    options: [
      { id: "a", label: "Use .sort() directly on the array" },
      { id: "b", label: "Use .map() / .filter() and return a new array" },
      { id: "c", label: "Assign new properties to the same object" },
      { id: "d", label: "Use delete on array indexes" },
    ],
    answerId: "b",
    explanation: "map/filter produce new collections without mutating the input.",
  },
  {
    id: "f-allsettled",
    prompt: "What does `Promise.allSettled` do compared with `Promise.all`?",
    options: [
      { id: "a", label: "Fails on the first rejection" },
      { id: "b", label: "Waits for all and reports fulfilled/rejected for each promise" },
      { id: "c", label: "Cancels the remaining promises" },
      { id: "d", label: "Only works with fetch" },
    ],
    answerId: "b",
    explanation: "allSettled does not stop at the first error.",
  },
  {
    id: "f-event-loop",
    prompt: "Which best describes the JavaScript event loop?",
    options: [
      { id: "a", label: "Multiple user threads running in parallel" },
      { id: "b", label: "A task queue + microtasks on a single thread" },
      { id: "c", label: "Only macros in Web Workers" },
      { id: "d", label: "Synchronous blocking of network I/O" },
    ],
    answerId: "b",
    explanation: "JS in the browser is single-threaded with an event loop.",
  },
  {
    id: "f-closure",
    prompt: "A closure allows you to:",
    options: [
      { id: "a", label: "Access variables from the outer scope even after the outer function has finished" },
      { id: "b", label: "Compile TypeScript to WebAssembly" },
      { id: "c", label: "Safely mutate the Array prototype globally" },
      { id: "d", label: "Avoid the garbage collector" },
    ],
    answerId: "a",
    explanation: "The inner function keeps a reference to the lexical environment.",
  },
  {
    id: "f-optional-chaining",
    prompt: "`user?.account?.balance` evaluates to undefined if:",
    options: [
      { id: "a", label: "user or account is null/undefined" },
      { id: "b", label: "balance is 0" },
      { id: "c", label: "balance is false" },
      { id: "d", label: "It always throws TypeError" },
    ],
    answerId: "a",
    explanation: "Optional chaining short-circuits on nullish values without throwing.",
  },
  {
    id: "f-nan",
    prompt: "What is the correct way to detect NaN?",
    options: [
      { id: "a", label: "value === NaN" },
      { id: "b", label: "Number.isNaN(value)" },
      { id: "c", label: "value == undefined" },
      { id: "d", label: "typeof value === 'nan'" },
    ],
    answerId: "b",
    explanation: "NaN !== NaN; Number.isNaN is the reliable check.",
  },
  {
    id: "f-set-unique",
    prompt: "To remove duplicates from an array of string IDs, the most idiomatic approach is:",
    options: [
      { id: "a", label: "[...new Set(ids)]" },
      { id: "b", label: "ids.sort()" },
      { id: "c", label: "ids.reverse()" },
      { id: "d", label: "ids.splice(0)" },
    ],
    answerId: "a",
    explanation: "Set stores unique values; the spread turns it back into an array.",
  },
  {
    id: "f-microtask",
    prompt: "A Promise.resolve().then(...) is queued as:",
    options: [
      { id: "a", label: "Macrotask (setTimeout)" },
      { id: "b", label: "Microtask" },
      { id: "c", label: "CSS task" },
      { id: "d", label: "Mandatory Worker thread" },
    ],
    answerId: "b",
    explanation: "Promise then callbacks go to the microtask queue.",
  },
  {
    id: "f-strict-equality",
    prompt: "`0 == '0'` and `0 === '0'` evaluate respectively to:",
    options: [
      { id: "a", label: "true and true" },
      { id: "b", label: "true and false" },
      { id: "c", label: "false and true" },
      { id: "d", label: "false and false" },
    ],
    answerId: "b",
    explanation: "== performs coercion; === does not.",
  },
  {
    id: "f-pure-function",
    prompt: "A pure function:",
    options: [
      { id: "a", label: "Depends only on its arguments and produces no side effects" },
      { id: "b", label: "Always writes to localStorage" },
      { id: "c", label: "Must use the component's this" },
      { id: "d", label: "Can only return void" },
    ],
    answerId: "a",
    explanation: "Same input -> same output, with no side effects.",
  },
  {
    id: "f-nullish",
    prompt: "`value ?? 'N/A'` uses the fallback when value is:",
    options: [
      { id: "a", label: "0 or ''" },
      { id: "b", label: "null or undefined" },
      { id: "c", label: "false" },
      { id: "d", label: "Any falsy value" },
    ],
    answerId: "b",
    explanation: "?? only reacts to nullish values, not all falsy values.",
  },
  {
    id: "f-array-reduce",
    prompt: "To calculate the total of a cart, the most expressive option is usually:",
    options: [
      { id: "a", label: "items.reduce((sum, i) => sum + i.price * i.qty, 0)" },
      { id: "b", label: "items.forEach without accumulating" },
      { id: "c", label: "items.pop() in a loop" },
      { id: "d", label: "items.splice(0, items.length)" },
    ],
    answerId: "a",
    explanation: "reduce accumulates a value from the collection.",
  },
  {
    id: "f-spread-object",
    prompt: "`const next = { ...user, role: 'admin' }` produces:",
    options: [
      { id: "a", label: "A shallow copy with role updated" },
      { id: "b", label: "In-place mutation of user" },
      { id: "c", label: "A mandatory Proxy" },
      { id: "d", label: "An error if user is nullish (always)" },
    ],
    answerId: "a",
    explanation: "Object spread creates a shallow clone and overwrites keys.",
  },
  {
    id: "f-promise-race",
    prompt: "`Promise.race` resolves/rejects with:",
    options: [
      { id: "a", label: "The result of the first promise that settles" },
      { id: "b", label: "All promises in parallel waiting for the last one" },
      { id: "c", label: "Only fulfilled values" },
      { id: "d", label: "Always an array" },
    ],
    answerId: "a",
    explanation: "Race takes the first settled promise.",
  },
  {
    id: "f-array-flatmap",
    prompt: "`flatMap` is useful when:",
    options: [
      { id: "a", label: "You map to arrays and want to flatten one level" },
      { id: "b", label: "You only sort numbers" },
      { id: "c", label: "You freeze the array" },
      { id: "d", label: "You replace JSON.parse" },
    ],
    answerId: "a",
    explanation: "map + flat(1) in a single step.",
  },
  {
    id: "f-typeof-null",
    prompt: "`typeof null` in JavaScript is:",
    options: [
      { id: "a", label: "'object' (historical quirk)" },
      { id: "b", label: "'null'" },
      { id: "c", label: "'undefined'" },
      { id: "d", label: "'nil'" },
    ],
    answerId: "a",
    explanation: "Legacy language bug: typeof null === 'object'.",
  },
  {
    id: "f-map-filter-diff",
    prompt: "Which returns an array of the same size by transforming each element?",
    options: [
      { id: "a", label: "map" },
      { id: "b", label: "filter" },
      { id: "c", label: "reduce" },
      { id: "d", label: "find" },
    ],
    answerId: "a",
    explanation: "map transforms 1:1; filter can reduce size.",
  },
  {
    id: "f-find-some-every",
    prompt: "`movs.some(m => m.amount < 0)` returns:",
    options: [
      { id: "a", label: "true if at least one element meets the condition" },
      { id: "b", label: "The first element that matches" },
      { id: "c", label: "A new filtered array" },
      { id: "d", label: "Always a number" },
    ],
    answerId: "a",
    explanation: "some/every return boolean; find returns the element.",
  },
  {
    id: "f-sort-slice-copy",
    prompt: "To sort without mutating the original array:",
    options: [
      { id: "a", label: "Clone ([...arr] or slice) and then sort the copy" },
      { id: "b", label: "sort() directly on the original" },
      { id: "c", label: "splice() on the original" },
      { id: "d", label: "delete on indexes" },
    ],
    answerId: "a",
    explanation: "Array.sort mutates in-place.",
  },
  {
    id: "f-async-await",
    prompt: "A function declared `async` always:",
    options: [
      { id: "a", label: "Returns a Promise" },
      { id: "b", label: "Blocks the browser's main thread" },
      { id: "c", label: "Cannot use try/catch" },
      { id: "d", label: "Cancels fetch automatically" },
    ],
    answerId: "a",
    explanation: "async wraps the return value in a Promise.",
  },
  {
    id: "f-destructuring",
    prompt: "`const { amount, date } = movement` is:",
    options: [
      { id: "a", label: "Object destructuring" },
      { id: "b", label: "Spread operator" },
      { id: "c", label: "Guaranteed deep cloning" },
      { id: "d", label: "Optional chaining" },
    ],
    answerId: "a",
    explanation: "It extracts properties by name.",
  }
];
