import type { McqQuestion } from "@/domain/exam";

/** MCQ bank Session 1 — JS / browser fundamentals */
export const mcqFundamentosExtra: McqQuestion[] = [
  {
    id: "f-spread-object",
    prompt: "`const next = { ...user, role: 'admin' }` produces:",
    options: [
      { id: "a", label: "A shallow copy with role updated" },
      { id: "b", label: "In-place mutation of user" },
      { id: "c", label: "A mandatory Proxy" },
      { id: "d", label: "An error if user is nullish (always)" },
    ],
    answerId: "a",
    explanation: "Object spread creates a shallow clone and overwrites keys.",
  },
  {
    id: "f-promise-race",
    prompt: "`Promise.race` resolves/rejects with:",
    options: [
      { id: "a", label: "The result of the first promise that settles" },
      { id: "b", label: "All promises in parallel waiting for the last one" },
      { id: "c", label: "Only fulfilled values" },
      { id: "d", label: "Always an array" },
    ],
    answerId: "a",
    explanation: "Race takes the first settled promise.",
  },
  {
    id: "f-array-flatmap",
    prompt: "`flatMap` is useful when:",
    options: [
      { id: "a", label: "You map to arrays and want to flatten one level" },
      { id: "b", label: "You only sort numbers" },
      { id: "c", label: "You freeze the array" },
      { id: "d", label: "You replace JSON.parse" },
    ],
    answerId: "a",
    explanation: "map + flat(1) in a single step.",
  },
  {
    id: "f-typeof-null",
    prompt: "`typeof null` in JavaScript is:",
    options: [
      { id: "a", label: "'object' (historical quirk)" },
      { id: "b", label: "'null'" },
      { id: "c", label: "'undefined'" },
      { id: "d", label: "'nil'" },
    ],
    answerId: "a",
    explanation: "Legacy language bug: typeof null === 'object'.",
  },
  {
    id: "f-structured-clone",
    prompt: "`structuredClone(value)` compared with JSON clone:",
    options: [
      { id: "a", label: "Preserves more types (Date, Map, etc.) without going through JSON" },
      { id: "b", label: "Only clones strings" },
      { id: "c", label: "Does not exist in modern browsers" },
      { id: "d", label: "Freezes the result" },
    ],
    answerId: "a",
    explanation: "Native API for structured deep cloning.",
  },
  {
    id: "f-weakmap",
    prompt: "One advantage of WeakMap is:",
    options: [
      { id: "a", label: "Object keys can be GC'd if there are no other refs" },
      { id: "b", label: "It is always iterable with for...of" },
      { id: "c", label: "It only accepts string keys" },
      { id: "d", label: "It persists in localStorage" },
    ],
    answerId: "a",
    explanation: "Weak refs avoid retaining objects unnecessarily.",
  },
  {
    id: "f-event-delegation",
    prompt: "Event delegation consists of:",
    options: [
      { id: "a", label: "Listening on an ancestor and filtering the target" },
      { id: "b", label: "Always registering one listener per cell" },
      { id: "c", label: "Using eval in the handler" },
      { id: "d", label: "Always blocking bubbling with alert" },
    ],
    answerId: "a",
    explanation: "One listener on the parent handles many children.",
  },
  {
    id: "f-module-import",
    prompt: "Dynamic `import()` returns:",
    options: [
      { id: "a", label: "A Promise that resolves to the module" },
      { id: "b", label: "The module synchronously every time" },
      { id: "c", label: "undefined" },
      { id: "d", label: "A Worker" },
    ],
    answerId: "a",
    explanation: "Code-splitting: import() is async.",
  },
  {
    id: "f-bignumber",
    prompt: "For exact monetary amounts in JS, it is best to:",
    options: [
      { id: "a", label: "Avoid binary float; use integers (cents) or decimal libs" },
      { id: "b", label: "Always use 0.1 + 0.2 without care" },
      { id: "c", label: "Store money as a boolean" },
      { id: "d", label: "Use Math.random for rounding" },
    ],
    answerId: "a",
    explanation: "IEEE-754 is not ideal for money.",
  },
  {
    id: "f-idempotent",
    prompt: "An idempotent payment API means:",
    options: [
      { id: "a", label: "Retrying with the same key does not duplicate the effect" },
      { id: "b", label: "It always charges twice" },
      { id: "c", label: "It cannot use HTTP" },
      { id: "d", label: "It ignores authentication" },
    ],
    answerId: "a",
    explanation: "Key concept for payments and network retries.",
  },
  {
    id: "f-csp",
    prompt: "Content-Security-Policy helps to:",
    options: [
      { id: "a", label: "Mitigate XSS by limiting script origins" },
      { id: "b", label: "Accelerate CSS Grid" },
      { id: "c", label: "Replace HTTPS" },
      { id: "d", label: "Compile TypeScript" },
    ],
    answerId: "a",
    explanation: "CSP controls what the browser can execute.",
  },
  {
    id: "f-aria-label",
    prompt: "An icon button with no visible text should have:",
    options: [
      { id: "a", label: "A descriptive aria-label (or sr-only text)" },
      { id: "b", label: "Only title in the HTML, always sufficient for WCAG" },
      { id: "c", label: "display:none on the button" },
      { id: "d", label: "Mandatory tabindex='-1'" },
    ],
    answerId: "a",
    explanation: "An accessible name for AT.",
  },
  {
    id: "f-map-filter-diff",
    prompt: "Which returns an array of the same size by transforming each element?",
    options: [
      { id: "a", label: "map" },
      { id: "b", label: "filter" },
      { id: "c", label: "reduce" },
      { id: "d", label: "find" },
    ],
    answerId: "a",
    explanation: "map transforms 1:1; filter can reduce size.",
  },
  {
    id: "f-find-some-every",
    prompt: "`movs.some(m => m.amount < 0)` returns:",
    options: [
      { id: "a", label: "true if at least one element meets the condition" },
      { id: "b", label: "The first element that matches" },
      { id: "c", label: "A new filtered array" },
      { id: "d", label: "Always a number" },
    ],
    answerId: "a",
    explanation: "some/every return boolean; find returns the element.",
  },
  {
    id: "f-sort-slice-copy",
    prompt: "To sort without mutating the original array:",
    options: [
      { id: "a", label: "Clone ([...arr] or slice) and then sort the copy" },
      { id: "b", label: "sort() directly on the original" },
      { id: "c", label: "splice() on the original" },
      { id: "d", label: "delete on indexes" },
    ],
    answerId: "a",
    explanation: "Array.sort mutates in-place.",
  },
  {
    id: "f-async-await",
    prompt: "A function declared `async` always:",
    options: [
      { id: "a", label: "Returns a Promise" },
      { id: "b", label: "Blocks the browser's main thread" },
      { id: "c", label: "Cannot use try/catch" },
      { id: "d", label: "Cancels fetch automatically" },
    ],
    answerId: "a",
    explanation: "async wraps the return value in a Promise.",
  },
  {
    id: "f-destructuring",
    prompt: "`const { amount, date } = movement` is:",
    options: [
      { id: "a", label: "Object destructuring" },
      { id: "b", label: "Spread operator" },
      { id: "c", label: "Guaranteed deep cloning" },
      { id: "d", label: "Optional chaining" },
    ],
    answerId: "a",
    explanation: "It extracts properties by name.",
  },
];
