import type { McqQuestion } from "@/domain/exam";

/** MCQ Bank Session 2 - Web / CSS / Angular / environment rules */
export const mcqWebBank: McqQuestion[] = [
  {
    id: "w-grid-autofit",
    prompt: "In CSS Grid, `grid-template-columns: repeat(auto-fit, minmax(220px, 1fr))` is used to:",
    options: [
      { id: "a", label: "Always fix exactly 3 columns" },
      { id: "b", label: "Create fluid columns that adapt to the available width" },
      { id: "c", label: "Disable responsiveness" },
      { id: "d", label: "Only work with Flexbox" },
    ],
    answerId: "b",
    explanation: "auto-fit + minmax creates a responsive layout.",
  },
  {
    id: "w-no-bds",
    prompt: "In Bancolombia's CSS layout test, what is prohibited?",
    options: [
      { id: "a", label: "Using native flexbox and grid" },
      { id: "b", label: "Using CSS frameworks or the bank's BDS" },
      { id: "c", label: "Using media queries" },
      { id: "d", label: "Using rem units" },
    ],
    answerId: "b",
    explanation: "You must build the layout from scratch, without frameworks or BDS.",
  },
  {
    id: "w-a11y-button",
    prompt: "An accessible button must, at minimum:",
    options: [
      { id: "a", label: "Have only an icon with no text or aria-label" },
      { id: "b", label: "Be keyboard-focusable and have an accessible name" },
      { id: "c", label: "Use div + onclick" },
      { id: "d", label: "Always be hidden with display:none" },
    ],
    answerId: "b",
    explanation: "Focus and an accessible name are WCAG basics.",
  },
  {
    id: "w-onpush",
    prompt: "In Angular, `ChangeDetectionStrategy.OnPush` means the component is checked when:",
    options: [
      { id: "a", label: "Any click anywhere in the document bubbles through Zone.js" },
      { id: "b", label: "Inputs change by reference, its own events fire, or manual marks occur" },
      { id: "c", label: "Never; detectChanges must always be forced on every tick" },
      { id: "d", label: "Only during server-side rendering hydration" },
    ],
    answerId: "b",
    explanation: "OnPush reduces checks to inputs/events/async/marks.",
  },
  {
    id: "w-no-reactive-forms",
    prompt: "In the test's Angular session, ReactiveFormsModule is:",
    options: [
      { id: "a", label: "Required" },
      { id: "b", label: "Prohibited; manual capture with $event or #templateRef" },
      { id: "c", label: "Only allowed in tests" },
      { id: "d", label: "Replaced by NgRx Forms" },
    ],
    answerId: "b",
    explanation: "Capture is 100% manual.",
  },
  {
    id: "w-locked-specs",
    prompt: "During the practical sessions, the unit test files:",
    options: [
      { id: "a", label: "Can be edited freely" },
      { id: "b", label: "Are locked; they grade automatically" },
      { id: "c", label: "Do not exist" },
      { id: "d", label: "Only run at the end of the day" },
    ],
    answerId: "b",
    explanation: "Specs are locked; they score your solution.",
  },
  {
    id: "w-trackby",
    prompt: "`*ngFor` with `trackBy` mainly helps to:",
    options: [
      { id: "a", label: "Improve DOM diffing when re-rendering lists" },
      { id: "b", label: "Avoid HttpClient" },
      { id: "c", label: "Activate Shadow DOM zones" },
      { id: "d", label: "Compile to WebAssembly" },
    ],
    answerId: "a",
    explanation: "trackBy identifies stable items.",
  },
  {
    id: "w-pass-70",
    prompt: "The minimum score to pass the technical test is:",
    options: [
      { id: "a", label: "50%" },
      { id: "b", label: "60%" },
      { id: "c", label: "70%" },
      { id: "d", label: "90%" },
    ],
    answerId: "c",
    explanation: "The passing target is at least 70%.",
  },
  {
    id: "w-flex-gap",
    prompt: "In modern Flexbox, `gap` is used to:",
    options: [
      { id: "a", label: "Space items without depending only on margins" },
      { id: "b", label: "Change the required stacking context" },
      { id: "c", label: "Disable flex-wrap" },
      { id: "d", label: "Only work in Grid, never in Flex" },
    ],
    answerId: "a",
    explanation: "gap defines the space between container items.",
  },
  {
    id: "w-em-vs-rem",
    prompt: "`rem` is calculated relative to:",
    options: [
      { id: "a", label: "The parent element's font-size" },
      { id: "b", label: "The root font-size (html)" },
      { id: "c", label: "The viewport width" },
      { id: "d", label: "The body's line-height" },
    ],
    answerId: "b",
    explanation: "rem = root em.",
  },
  {
    id: "w-semantic-html",
    prompt: "For primary navigation, the preferred semantic element is:",
    options: [
      { id: "a", label: "<div class='nav'>" },
      { id: "b", label: "<nav>" },
      { id: "c", label: "<span>" },
      { id: "d", label: "<b>" },
    ],
    answerId: "b",
    explanation: "<nav> communicates the navigation role to AT.",
  },
  {
    id: "w-ngonchanges",
    prompt: "`ngOnChanges` fires when:",
    options: [
      { id: "a", label: "The component's @Input() values change" },
      { id: "b", label: "Only when destroying the component" },
      { id: "c", label: "Only with Reactive Forms" },
      { id: "d", label: "Never in OnPush" },
    ],
    answerId: "a",
    explanation: "Lifecycle hook tied to input changes.",
  },
  {
    id: "w-subject-vs-behavior",
    prompt: "Unlike Subject, a BehaviorSubject:",
    options: [
      { id: "a", label: "Requires an initial value and re-emits the latest one to new subscribers" },
      { id: "b", label: "Cannot emit errors" },
      { id: "c", label: "Only works in Zone.js" },
      { id: "d", label: "Is a single synchronous value with no multicast" },
    ],
    answerId: "a",
    explanation: "BehaviorSubject stores the latest value.",
  },
  {
    id: "w-css-specificity",
    prompt: "Of `#id`, `.class`, and `element`, the highest specificity belongs to:",
    options: [
      { id: "a", label: "element" },
      { id: "b", label: ".class" },
      { id: "c", label: "#id" },
      { id: "d", label: "All are equal" },
    ],
    answerId: "c",
    explanation: "IDs outrank classes and elements.",
  },
  {
    id: "w-aria-live",
    prompt: "`aria-live=\"polite\"` is used to:",
    options: [
      { id: "a", label: "Announce dynamic changes to screen readers without abruptly interrupting" },
      { id: "b", label: "Hide the element visually" },
      { id: "c", label: "Force focus on load" },
      { id: "d", label: "Disable CSS transitions" },
    ],
    answerId: "a",
    explanation: "Live regions announce updates in a non-aggressive way.",
  },
  {
    id: "w-template-ref",
    prompt: "In Angular, a `#accountInput` reference in the template lets you:",
    options: [
      { id: "a", label: "Read the DOM/control from the template or ViewChild" },
      { id: "b", label: "Create a FormControl automatically" },
      { id: "c", label: "Import ReactiveFormsModule" },
      { id: "d", label: "Replace the component selector" },
    ],
    answerId: "a",
    explanation: "Template refs expose the element/directive.",
  },
  {
    id: "w-box-sizing",
    prompt: "`box-sizing: border-box` makes width include:",
    options: [
      { id: "a", label: "Only the content" },
      { id: "b", label: "Content + padding + border" },
      { id: "c", label: "Only margin" },
      { id: "d", label: "Only outline" },
    ],
    answerId: "b",
    explanation: "border-box includes padding/border in the width.",
  },
  {
    id: "w-httpclient",
    prompt: "In Angular, the framework's standard HTTP client is:",
    options: [
      { id: "a", label: "HttpClient (from @angular/common/http)" },
      { id: "b", label: "HttpModule from AngularJS 1.x (still required in v17+)" },
      { id: "c", label: "fetch only — HttpClient was removed in Ivy" },
      { id: "d", label: "XMLHttpRequestService provided by Zone.js" },
    ],
    answerId: "a",
    explanation: "HttpClient is the recommended Angular API for HTTP.",
  },
  {
    id: "w-pure-css-no-tailwind",
    prompt: "If the session prohibits CSS frameworks, which one should you NOT use?",
    options: [
      { id: "a", label: "display: flex" },
      { id: "b", label: "Tailwind utility classes" },
      { id: "c", label: "media queries" },
      { id: "d", label: "CSS variables" },
    ],
    answerId: "b",
    explanation: "Tailwind is out of scope in the pure CSS session.",
  },
  {
    id: "w-ngfor-async",
    prompt: "The `async` pipe in an Angular template:",
    options: [
      { id: "a", label: "Subscribes to an Observable/Promise and unsubscribes when the view is destroyed" },
      { id: "b", label: "Converts strings to JSON" },
      { id: "c", label: "Activates Reactive Forms" },
      { id: "d", label: "Only works with Set" },
    ],
    answerId: "a",
    explanation: "The async pipe manages the subscription safely.",
  },
  {
    id: "w-position-sticky",
    prompt: "`position: sticky` is useful for:",
    options: [
      { id: "a", label: "Headers that stick while scrolling inside their container" },
      { id: "b", label: "Always replacing Grid" },
      { id: "c", label: "Removing the stacking context" },
      { id: "d", label: "Disabling overflow" },
    ],
    answerId: "a",
    explanation: "sticky combines normal flow with fixing at a threshold.",
  },
  {
    id: "w-exam-hours",
    prompt: "The total time for the technical test is:",
    options: [
      { id: "a", label: "1 hour" },
      { id: "b", label: "2 hours" },
      { id: "c", label: "3 hours" },
      { id: "d", label: "8 hours" },
    ],
    answerId: "c",
    explanation: "Exactly 3 hours for the whole test.",
  },
  {
    id: "w-sessions-count",
    prompt: "How many sessions does the test have in total?",
    options: [
      { id: "a", label: "3 practical only" },
      { id: "b", label: "5 (2 MCQ + 3 practical)" },
      { id: "c", label: "10 random" },
      { id: "d", label: "1 single session" },
    ],
    answerId: "b",
    explanation: "2 theory sessions + 3 development sessions.",
  },
  {
    id: "w-hostlistener",
    prompt: "`@HostListener('keydown.enter')` in an Angular directive:",
    options: [
      { id: "a", label: "Listens for the event on the directive's host" },
      { id: "b", label: "Creates a FormGroup" },
      { id: "c", label: "Only works with native Shadow DOM" },
      { id: "d", label: "Replaces zone.js" },
    ],
    answerId: "a",
    explanation: "HostListener binds listeners to the host element.",
  },
  {
    id: "w-display-flow",
    prompt: "`display: block` makes the element:",
    options: [
      { id: "a", label: "Take up the available width on its own flow line" },
      { id: "b", label: "Always ignore width and height" },
      { id: "c", label: "Be invisible while preserving space (visibility)" },
      { id: "d", label: "Only work inside Grid" },
    ],
    answerId: "a",
    explanation: "block starts a new line; inline follows the text.",
  },
  {
    id: "w-overflow-scroll",
    prompt: "Internal scrolling in a long list without breaking the layout:",
    options: [
      { id: "a", label: "max-height + overflow-y: auto" },
      { id: "b", label: "display: none on the parent" },
      { id: "c", label: "position: fixed on each item" },
      { id: "d", label: "float: left on all children" },
    ],
    answerId: "a",
    explanation: "Bounded container with controlled overflow.",
  },
  {
    id: "w-pseudo-media",
    prompt: "`:hover` and `@media (min-width: 768px)` are used for:",
    options: [
      { id: "a", label: "Interactive states and responsive design" },
      { id: "b", label: "Compiling TypeScript to CSS" },
      { id: "c", label: "Replacing flexbox" },
      { id: "d", label: "Always avoiding specificity" },
    ],
    answerId: "a",
    explanation: "Pseudo-classes + media queries without JS.",
  },
  {
    id: "w-ngoninit",
    prompt: "`ngOnInit` is the right hook for:",
    options: [
      { id: "a", label: "Initializing data after creating the component (fetch, state)" },
      { id: "b", label: "Unsubscribing Observables" },
      { id: "c", label: "Registering ReactiveFormsModule" },
      { id: "d", label: "Compiling the template AOT" },
    ],
    answerId: "a",
    explanation: "Initial setup; no heavy side effects in the constructor.",
  },
  {
    id: "w-ngondestroy",
    prompt: "`ngOnDestroy` should mainly be used to:",
    options: [
      { id: "a", label: "Clean up subscriptions, timers, and listeners" },
      { id: "b", label: "Create new @Input values" },
      { id: "c", label: "Activate FormGroup" },
      { id: "d", label: "Switch to OnPush automatically" },
    ],
    answerId: "a",
    explanation: "Prevents memory leaks when destroying the component.",
  },
  {
    id: "w-signals",
    prompt: "`count = signal(0)` in Angular and reading `count()` in the template:",
    options: [
      { id: "a", label: "Reactive state consumed as a function" },
      { id: "b", label: "Replaces HttpClient by default" },
      { id: "c", label: "Freezes the value permanently" },
      { id: "d", label: "Only works without Zone.js and without tests" },
    ],
    answerId: "a",
    explanation: "Signals: set/update and read with ().",
  },
  {
    id: "w-input-output",
    prompt: "`@Output() save = new EventEmitter<T>()` is used to:",
    options: [
      { id: "a", label: "Notify the parent component about child events" },
      { id: "b", label: "Mutate the parent's @Input directly" },
      { id: "c", label: "Create an automatic FormGroup" },
      { id: "d", label: "Disable change detection" },
    ],
    answerId: "a",
    explanation: "Output = events upward.",
  },
  {
    id: "w-afterviewinit",
    prompt: "`ngAfterViewInit` is safe for:",
    options: [
      { id: "a", label: "Using an already rendered @ViewChild (focus, DOM measurements)" },
      { id: "b", label: "Defining @Input for the first time" },
      { id: "c", label: "Running ngOnDestroy" },
      { id: "d", label: "Lazy-loading the root module" },
    ],
    answerId: "a",
    explanation: "The child view already exists; ViewChild is available.",
  },
  {
    id: "w-ngif-directive",
    prompt: "`*ngIf=\"visible\"` in an Angular template:",
    options: [
      { id: "a", label: "Mounts or unmounts the node based on the condition" },
      { id: "b", label: "Only toggles CSS visibility while keeping the node mounted" },
      { id: "c", label: "Is a synonym of [hidden] and never destroys views" },
      { id: "d", label: "Replaces trackBy and is required on every *ngFor" },
    ],
    answerId: "a",
    explanation: "Conditional structural directive — false removes the view from the DOM.",
  },
];
