import type { McqQuestion } from "@/domain/exam";

/** Banco MCQ — SQL (conceptos bancarios / consultas) */
export const mcqSqlBank: McqQuestion[] = [
  {
    id: "sql-select-basic",
    prompt: "¿Qué hace `SELECT amount FROM movements WHERE amount > 0`?",
    options: [
      { id: "a", label: "Elimina movimientos positivos" },
      { id: "b", label: "Devuelve la columna amount de filas con amount positivo" },
      { id: "c", label: "Actualiza todos los montos a 0" },
      { id: "d", label: "Crea un índice en amount" },
    ],
    answerId: "b",
    explanation: "SELECT proyecta columnas; WHERE filtra filas.",
  },
  {
    id: "sql-join-inner",
    prompt: "Un `INNER JOIN` entre cuentas y movimientos retorna:",
    options: [
      { id: "a", label: "Todas las cuentas aunque no tengan movimientos" },
      { id: "b", label: "Solo filas con coincidencia en ambas tablas" },
      { id: "c", label: "Solo filas de la tabla izquierda" },
      { id: "d", label: "Un producto cartesiano completo siempre" },
    ],
    answerId: "b",
    explanation: "INNER JOIN exige match en la condición de unión.",
  },
  {
    id: "sql-left-join",
    prompt: "`LEFT JOIN movements ON ...` desde accounts sirve para:",
    options: [
      { id: "a", label: "Traer todas las cuentas y sus movimientos (null si no hay)" },
      { id: "b", label: "Borrar cuentas sin movimientos" },
      { id: "c", label: "Forzar solo cuentas con saldo negativo" },
      { id: "d", label: "Crear una vista materializada" },
    ],
    answerId: "a",
    explanation: "LEFT preserva todas las filas de la tabla izquierda.",
  },
  {
    id: "sql-group-by",
    prompt: "Para totalizar gastos por categoría la forma correcta es:",
    options: [
      { id: "a", label: "SELECT category, SUM(amount) FROM tx GROUP BY category" },
      { id: "b", label: "SELECT category, SUM(amount) FROM tx" },
      { id: "c", label: "SELECT * FROM tx ORDER BY amount" },
      { id: "d", label: "DELETE FROM tx GROUP BY category" },
    ],
    answerId: "a",
    explanation: "Agregaciones con columnas no agregadas requieren GROUP BY.",
  },
  {
    id: "sql-having",
    prompt: "`HAVING` se diferencia de `WHERE` porque:",
    options: [
      { id: "a", label: "Filtra después de agrupar (sobre agregados)" },
      { id: "b", label: "Solo funciona con DELETE" },
      { id: "c", label: "Es más rápido siempre que WHERE" },
      { id: "d", label: "No puede usar COUNT/SUM" },
    ],
    answerId: "a",
    explanation: "WHERE filtra filas; HAVING filtra grupos.",
  },
  {
    id: "sql-index",
    prompt: "Un índice en `movements(account_id, date)` ayuda principalmente a:",
    options: [
      { id: "a", label: "Consultas que filtran/ordenan por cuenta y fecha" },
      { id: "b", label: "Reducir el tamaño del disco siempre a la mitad" },
      { id: "c", label: "Evitar escribir INSERT" },
      { id: "d", label: "Reemplazar la primary key" },
    ],
    answerId: "a",
    explanation: "Índices compuestos aceleran predicados/order que siguen el prefijo.",
  },
  {
    id: "sql-pk-unique",
    prompt: "La PRIMARY KEY de una tabla de transacciones garantiza:",
    options: [
      { id: "a", label: "Valores únicos y no nulos que identifican cada fila" },
      { id: "b", label: "Que amount sea siempre positivo" },
      { id: "c", label: "Que no existan foreign keys" },
      { id: "d", label: "Orden alfabético automático" },
    ],
    answerId: "a",
    explanation: "PK = identidad única + NOT NULL.",
  },
  {
    id: "sql-fk",
    prompt: "Una FOREIGN KEY de `movements.account_id` hacia `accounts.id` sirve para:",
    options: [
      { id: "a", label: "Integridad referencial entre movimientos y cuentas" },
      { id: "b", label: "Autocompletar UI en Angular" },
      { id: "c", label: "Cifrar el amount" },
      { id: "d", label: "Crear un trigger de backup" },
    ],
    answerId: "a",
    explanation: "FK evita referencias huérfanas (según reglas ON DELETE/UPDATE).",
  },
  {
    id: "sql-null",
    prompt: "En SQL, `amount = NULL` evalúa a:",
    options: [
      { id: "a", label: "TRUE si amount es null" },
      { id: "b", label: "UNKNOWN; se usa `amount IS NULL`" },
      { id: "c", label: "FALSE siempre" },
      { id: "d", label: "Error de sintaxis en todos los motores" },
    ],
    answerId: "b",
    explanation: "Comparar con NULL no funciona con =; usa IS NULL.",
  },
  {
    id: "sql-order-limit",
    prompt: "Para los 10 movimientos más recientes de una cuenta:",
    options: [
      { id: "a", label: "ORDER BY date DESC LIMIT 10" },
      { id: "b", label: "GROUP BY date LIMIT 10" },
      { id: "c", label: "DISTINCT date ASC" },
      { id: "d", label: "UNION ALL LIMIT 10" },
    ],
    answerId: "a",
    explanation: "Orden descendente + LIMIT (o FETCH FIRST según dialéctica).",
  },
  {
    id: "sql-distinct",
    prompt: "`SELECT DISTINCT company FROM applications` retorna:",
    options: [
      { id: "a", label: "Valores únicos de company" },
      { id: "b", label: "Solo el primer registro de la tabla" },
      { id: "c", label: "Un conteo de companies" },
      { id: "d", label: "Todas las filas duplicadas" },
    ],
    answerId: "a",
    explanation: "DISTINCT elimina duplicados del resultado proyectado.",
  },
  {
    id: "sql-transaction",
    prompt: "En una transferencia entre dos cuentas, ¿por qué usar una transacción?",
    options: [
      { id: "a", label: "Para que débito y crédito se confirmen juntos (atomicidad)" },
      { id: "b", label: "Para evitar índices" },
      { id: "c", label: "Para desactivar el WHERE" },
      { id: "d", label: "Solo por estilo de código" },
    ],
    answerId: "a",
    explanation: "ACID: o se aplican ambos cambios o ninguno.",
  },
  {
    id: "sql-commit-rollback",
    prompt: "`ROLLBACK` en una transacción abierta:",
    options: [
      { id: "a", label: "Confirma los cambios" },
      { id: "b", label: "Deshace los cambios no confirmados" },
      { id: "c", label: "Crea un savepoint permanente" },
      { id: "d", label: "Vacía toda la base" },
    ],
    answerId: "b",
    explanation: "ROLLBACK revierte; COMMIT confirma.",
  },
  {
    id: "sql-aggregate-count",
    prompt: "`COUNT(*)` vs `COUNT(email)` cuando email puede ser NULL:",
    options: [
      { id: "a", label: "COUNT(*) cuenta filas; COUNT(email) ignora NULL en email" },
      { id: "b", label: "Son siempre idénticos" },
      { id: "c", label: "COUNT(email) cuenta más filas" },
      { id: "d", label: "COUNT(*) no existe en SQL estándar" },
    ],
    answerId: "a",
    explanation: "COUNT(col) no cuenta NULLs; COUNT(*) sí filas.",
  },
  {
    id: "sql-between",
    prompt: "`amount BETWEEN 100 AND 200` es equivalente a:",
    options: [
      { id: "a", label: "amount >= 100 AND amount <= 200" },
      { id: "b", label: "amount > 100 AND amount < 200" },
      { id: "c", label: "amount = 100 OR amount = 200" },
      { id: "d", label: "amount IN (100)" },
    ],
    answerId: "a",
    explanation: "BETWEEN es inclusivo en ambos extremos.",
  },
  {
    id: "sql-like",
    prompt: "Para buscar descripciones que empiecen por 'PSE' en SQL estándar:",
    options: [
      { id: "a", label: "description LIKE 'PSE%'" },
      { id: "b", label: "description = 'PSE*'" },
      { id: "c", label: "description CONTAINS PSE" },
      { id: "d", label: "description REGEX PSE solo obligatorio" },
    ],
    answerId: "a",
    explanation: "% es comodín de LIKE para cualquier cola.",
  },
  {
    id: "sql-subquery",
    prompt: "Una subconsulta en `WHERE account_id IN (SELECT id FROM accounts WHERE status='ACTIVE')`:",
    options: [
      { id: "a", label: "Filtra movimientos cuyas cuentas están activas" },
      { id: "b", label: "Borra cuentas inactivas" },
      { id: "c", label: "Crea un índice automáticamente" },
      { id: "d", label: "Solo funciona con FULL OUTER JOIN" },
    ],
    answerId: "a",
    explanation: "El IN recibe el set de ids activos.",
  },
  {
    id: "sql-view",
    prompt: "Una VIEW en SQL es:",
    options: [
      { id: "a", label: "Una consulta guardada que se consulta como tabla" },
      { id: "b", label: "Una copia física obligatoria de todos los datos" },
      { id: "c", label: "Un trigger de auditoría" },
      { id: "d", label: "Un tipo de índice hash" },
    ],
    answerId: "a",
    explanation: "Vista = query nombrada (salvo materializada).",
  },
  {
    id: "sql-normalization",
    prompt: "Normalizar tablas de un core bancario busca principalmente:",
    options: [
      { id: "a", label: "Reducir redundancia e inconsistencias" },
      { id: "b", label: "Duplicar saldos en cada fila" },
      { id: "c", label: "Eliminar todas las foreign keys" },
      { id: "d", label: "Guardar JSON sin estructura" },
    ],
    answerId: "a",
    explanation: "Normalización organiza dependencias y evita anomalías.",
  },
  {
    id: "sql-explain",
    prompt: "`EXPLAIN` / plan de ejecución se usa para:",
    options: [
      { id: "a", label: "Entender cómo el motor accederá a los datos (índices, scans)" },
      { id: "b", label: "Ejecutar COMMIT automático" },
      { id: "c", label: "Crear usuarios" },
      { id: "d", label: "Validar CSS" },
    ],
    answerId: "a",
    explanation: "Sirve para optimizar consultas.",
  },
  {
    id: "sql-union",
    prompt: "`UNION` vs `UNION ALL`:",
    options: [
      { id: "a", label: "UNION elimina duplicados; UNION ALL los conserva" },
      { id: "b", label: "Son idénticos" },
      { id: "c", label: "UNION ALL es más estricto con tipos" },
      { id: "d", label: "UNION solo funciona con INSERT" },
    ],
    answerId: "a",
    explanation: "UNION hace DISTINCT implícito entre sets.",
  },
  {
    id: "sql-window",
    prompt: "`SUM(amount) OVER (PARTITION BY account_id ORDER BY date)` calcula:",
    options: [
      { id: "a", label: "Un running total por cuenta sin colapsar filas" },
      { id: "b", label: "Un DELETE por partición" },
      { id: "c", label: "Solo el máximo global" },
      { id: "d", label: "Un índice parcial" },
    ],
    answerId: "a",
    explanation: "Funciones ventana agregan conservando el detalle.",
  },
  {
    id: "sql-case",
    prompt: "Para etiquetar movimientos como 'crédito'/'débito' según el signo:",
    options: [
      { id: "a", label: "CASE WHEN amount >= 0 THEN 'crédito' ELSE 'débito' END" },
      { id: "b", label: "IF amount THEN crédito (válido en todo SQL estándar puro)" },
      { id: "c", label: "SWITCH(amount)" },
      { id: "d", label: "DECODE solo en MongoDB" },
    ],
    answerId: "a",
    explanation: "CASE es la expresión condicional portátil.",
  },
  {
    id: "sql-injection",
    prompt: "Para evitar SQL injection en una app bancaria debes:",
    options: [
      { id: "a", label: "Usar parámetros preparados / bind variables" },
      { id: "b", label: "Concatenar el input del usuario en el SQL" },
      { id: "c", label: "Desactivar el WHERE" },
      { id: "d", label: "Exponer la connection string al frontend" },
    ],
    answerId: "a",
    explanation: "Prepared statements separan código de datos.",
  },
  {
    id: "sql-avg",
    prompt: "`AVG(amount)` sobre una columna con NULLs:",
    options: [
      { id: "a", label: "Ignora NULLs en el promedio" },
      { id: "b", label: "Trata NULL como 0 siempre" },
      { id: "c", label: "Falla si hay un NULL" },
      { id: "d", label: "Solo funciona con DISTINCT obligatorio" },
    ],
    answerId: "a",
    explanation: "Agregados numéricos típicos omiten NULL.",
  },
  {
    id: "sql-alias",
    prompt: "`SELECT SUM(amount) AS total FROM movements` — `total` es:",
    options: [
      { id: "a", label: "Un alias de columna en el result set" },
      { id: "b", label: "Una tabla temporal física" },
      { id: "c", label: "Una primary key" },
      { id: "d", label: "Un stored procedure" },
    ],
    answerId: "a",
    explanation: "AS renombra la columna del resultado.",
  },
  {
    id: "sql-delete-where",
    prompt: "¿Qué riesgo tiene `DELETE FROM movements` sin WHERE?",
    options: [
      { id: "a", label: "Puede borrar todas las filas de la tabla" },
      { id: "b", label: "Solo borra la primera fila" },
      { id: "c", label: "No hace nada" },
      { id: "d", label: "Convierte la tabla en VIEW" },
    ],
    answerId: "a",
    explanation: "Sin WHERE el DELETE aplica a toda la tabla.",
  },
  {
    id: "sql-update",
    prompt: "Actualizar el estado de una cuenta específica requiere:",
    options: [
      { id: "a", label: "UPDATE accounts SET status='BLOCKED' WHERE id = ?" },
      { id: "b", label: "UPDATE accounts SET status='BLOCKED'" },
      { id: "c", label: "SELECT status FROM accounts WHERE id = ?" },
      { id: "d", label: "ALTER TABLE accounts BLOCK id" },
    ],
    answerId: "a",
    explanation: "UPDATE + WHERE acota el cambio.",
  },
  {
    id: "sql-coalesce",
    prompt: "`COALESCE(nickname, full_name, 'Cliente')` retorna:",
    options: [
      { id: "a", label: "El primer valor no NULL de la lista" },
      { id: "b", label: "Siempre 'Cliente'" },
      { id: "c", label: "La concatenación de los tres" },
      { id: "d", label: "Un error si nickname es NULL" },
    ],
    answerId: "a",
    explanation: "COALESCE elige el primer no nulo.",
  },
  {
    id: "sql-exists",
    prompt: "`WHERE EXISTS (SELECT 1 FROM movements m WHERE m.account_id = a.id)`:",
    options: [
      { id: "a", label: "Filtra cuentas que tienen al menos un movimiento" },
      { id: "b", label: "Cuenta todos los movimientos" },
      { id: "c", label: "Crea la cuenta si no existe" },
      { id: "d", label: "Ordena por id" },
    ],
    answerId: "a",
    explanation: "EXISTS corta al encontrar la primera coincidencia.",
  },
];
