import type { McqQuestion } from "@/domain/exam";

/** Banco MCQ Sesión 2 — Web / CSS / Angular / reglas del entorno */
export const mcqWebBank: McqQuestion[] = [
  {
    id: "w-grid-autofit",
    prompt: "En CSS Grid, `grid-template-columns: repeat(auto-fit, minmax(220px, 1fr))` sirve para:",
    options: [
      { id: "a", label: "Fijar exactamente 3 columnas siempre" },
      { id: "b", label: "Crear columnas fluidas que se ajustan al ancho disponible" },
      { id: "c", label: "Desactivar el responsive" },
      { id: "d", label: "Solo funciona con Flexbox" },
    ],
    answerId: "b",
    explanation: "auto-fit + minmax genera layout responsive.",
  },
  {
    id: "w-no-bds",
    prompt: "En la prueba de maquetación CSS de Bancolombia, ¿qué está prohibido?",
    options: [
      { id: "a", label: "Usar flexbox y grid nativos" },
      { id: "b", label: "Usar frameworks CSS o el BDS del banco" },
      { id: "c", label: "Usar media queries" },
      { id: "d", label: "Usar unidades rem" },
    ],
    answerId: "b",
    explanation: "Debes maquetar desde cero, sin frameworks ni BDS.",
  },
  {
    id: "w-a11y-button",
    prompt: "Un botón accesible debe, como mínimo:",
    options: [
      { id: "a", label: "Tener solo un ícono sin texto ni aria-label" },
      { id: "b", label: "Ser enfocable por teclado y tener nombre accesible" },
      { id: "c", label: "Usar div + onclick" },
      { id: "d", label: "Ocultarse con display:none siempre" },
    ],
    answerId: "b",
    explanation: "Enfoque + nombre accesible son básicos WCAG.",
  },
  {
    id: "w-onpush",
    prompt: "En Angular, `ChangeDetectionStrategy.OnPush` implica que el componente se verifica cuando:",
    options: [
      { id: "a", label: "Cualquier evento global ocurre siempre" },
      { id: "b", label: "Cambian inputs por referencia, eventos propios o marcas manuales" },
      { id: "c", label: "Nunca, hay que forzar detectChanges siempre" },
      { id: "d", label: "Solo en SSR" },
    ],
    answerId: "b",
    explanation: "OnPush reduce chequeos a inputs/eventos/marks.",
  },
  {
    id: "w-no-reactive-forms",
    prompt: "En la sesión Angular de la prueba, ReactiveFormsModule está:",
    options: [
      { id: "a", label: "Obligatorio" },
      { id: "b", label: "Prohibido; captura manual con $event o #templateRef" },
      { id: "c", label: "Solo permitido en tests" },
      { id: "d", label: "Reemplazado por NgRx Forms" },
    ],
    answerId: "b",
    explanation: "Captura 100% manual.",
  },
  {
    id: "w-locked-specs",
    prompt: "Durante las sesiones prácticas, los archivos de pruebas unitarias:",
    options: [
      { id: "a", label: "Se pueden editar libremente" },
      { id: "b", label: "Están bloqueados; califican de forma automática" },
      { id: "c", label: "No existen" },
      { id: "d", label: "Solo se corren al final del día" },
    ],
    answerId: "b",
    explanation: "Specs locked; puntúan tu solución.",
  },
  {
    id: "w-trackby",
    prompt: "`*ngFor` con `trackBy` ayuda principalmente a:",
    options: [
      { id: "a", label: "Mejorar diferencial de DOM al re-renderizar listas" },
      { id: "b", label: "Evitar HttpClient" },
      { id: "c", label: "Activar zonas de Shadow DOM" },
      { id: "d", label: "Compilar a WebAssembly" },
    ],
    answerId: "a",
    explanation: "trackBy identifica ítems estables.",
  },
  {
    id: "w-pass-70",
    prompt: "El puntaje mínimo para aprobar la prueba técnica es:",
    options: [
      { id: "a", label: "50%" },
      { id: "b", label: "60%" },
      { id: "c", label: "70%" },
      { id: "d", label: "90%" },
    ],
    answerId: "c",
    explanation: "Meta de aprobación ≥ 70%.",
  },
  {
    id: "w-flex-gap",
    prompt: "En Flexbox moderno, `gap` sirve para:",
    options: [
      { id: "a", label: "Espaciar ítems sin depender solo de margins" },
      { id: "b", label: "Cambiar el stacking context obligatorio" },
      { id: "c", label: "Desactivar flex-wrap" },
      { id: "d", label: "Solo funciona en Grid, nunca en Flex" },
    ],
    answerId: "a",
    explanation: "gap define espacio entre ítems del contenedor.",
  },
  {
    id: "w-em-vs-rem",
    prompt: "`rem` se calcula relativo a:",
    options: [
      { id: "a", label: "El font-size del elemento padre" },
      { id: "b", label: "El font-size de la raíz (html)" },
      { id: "c", label: "El viewport width" },
      { id: "d", label: "El line-height del body" },
    ],
    answerId: "b",
    explanation: "rem = root em.",
  },
  {
    id: "w-semantic-html",
    prompt: "Para una navegación principal, el elemento semántico preferido es:",
    options: [
      { id: "a", label: "<div class='nav'>" },
      { id: "b", label: "<nav>" },
      { id: "c", label: "<span>" },
      { id: "d", label: "<b>" },
    ],
    answerId: "b",
    explanation: "<nav> comunica rol de navegación a AT.",
  },
  {
    id: "w-ngonchanges",
    prompt: "`ngOnChanges` se dispara cuando:",
    options: [
      { id: "a", label: "Cambian @Input() del componente" },
      { id: "b", label: "Solo al destruir el componente" },
      { id: "c", label: "Solo con Reactive Forms" },
      { id: "d", label: "Nunca en OnPush" },
    ],
    answerId: "a",
    explanation: "Lifecycle hook ligado a cambios de inputs.",
  },
  {
    id: "w-subject-vs-behavior",
    prompt: "Un BehaviorSubject a diferencia de Subject:",
    options: [
      { id: "a", label: "Requiere valor inicial y reemite el último a nuevos subscribers" },
      { id: "b", label: "No puede emitir errores" },
      { id: "c", label: "Solo funciona en Zone.js" },
      { id: "d", label: "Es síncrono único sin multicast" },
    ],
    answerId: "a",
    explanation: "BehaviorSubject guarda el último valor.",
  },
  {
    id: "w-css-specificity",
    prompt: "Entre `#id`, `.class` y `element`, la mayor especificidad la tiene:",
    options: [
      { id: "a", label: "element" },
      { id: "b", label: ".class" },
      { id: "c", label: "#id" },
      { id: "d", label: "Todas igual" },
    ],
    answerId: "c",
    explanation: "IDs ganan a clases y elementos.",
  },
  {
    id: "w-aria-live",
    prompt: "`aria-live=\"polite\"` se usa para:",
    options: [
      { id: "a", label: "Anunciar cambios dinámicos a lectores de pantalla sin interrumpir de golpe" },
      { id: "b", label: "Ocultar el elemento visualmente" },
      { id: "c", label: "Forzar foco al cargar" },
      { id: "d", label: "Desactivar CSS transitions" },
    ],
    answerId: "a",
    explanation: "Regiones live anuncian updates de forma no agresiva.",
  },
  {
    id: "w-template-ref",
    prompt: "En Angular, una referencia `#accountInput` en el template permite:",
    options: [
      { id: "a", label: "Leer el DOM/control desde el template o ViewChild" },
      { id: "b", label: "Crear un FormControl automáticamente" },
      { id: "c", label: "Importar ReactiveFormsModule" },
      { id: "d", label: "Sustituir el selector del componente" },
    ],
    answerId: "a",
    explanation: "Template refs exponen el elemento/directiva.",
  },
  {
    id: "w-box-sizing",
    prompt: "`box-sizing: border-box` hace que width incluya:",
    options: [
      { id: "a", label: "Solo el contenido" },
      { id: "b", label: "Contenido + padding + border" },
      { id: "c", label: "Solo margin" },
      { id: "d", label: "Solo outline" },
    ],
    answerId: "b",
    explanation: "border-box incluye padding/border en el width.",
  },
  {
    id: "w-httpclient",
    prompt: "En Angular, el cliente HTTP estándar del framework es:",
    options: [
      { id: "a", label: "HttpClient" },
      { id: "b", label: "XMLHttpRequestService obligatorio" },
      { id: "c", label: "jquery.ajax" },
      { id: "d", label: "fetch module de Node" },
    ],
    answerId: "a",
    explanation: "HttpClient es el API recomendado.",
  },
  {
    id: "w-pure-css-no-tailwind",
    prompt: "Si la sesión prohíbe frameworks CSS, ¿cuál NO debes usar?",
    options: [
      { id: "a", label: "display: flex" },
      { id: "b", label: "Tailwind utility classes" },
      { id: "c", label: "media queries" },
      { id: "d", label: "CSS variables" },
    ],
    answerId: "b",
    explanation: "Tailwind está fuera de alcance en la sesión CSS pura.",
  },
  {
    id: "w-ngfor-async",
    prompt: "El pipe `async` en un template Angular:",
    options: [
      { id: "a", label: "Se suscribe a Observable/Promise y se desuscribe al destruir la vista" },
      { id: "b", label: "Convierte strings a JSON" },
      { id: "c", label: "Activa Reactive Forms" },
      { id: "d", label: "Solo funciona con Set" },
    ],
    answerId: "a",
    explanation: "async pipe gestiona la suscripción de forma segura.",
  },
  {
    id: "w-position-sticky",
    prompt: "`position: sticky` es útil para:",
    options: [
      { id: "a", label: "Encabezados que se fijan al hacer scroll dentro de su contenedor" },
      { id: "b", label: "Reemplazar siempre a Grid" },
      { id: "c", label: "Eliminar el stacking context" },
      { id: "d", label: "Desactivar overflow" },
    ],
    answerId: "a",
    explanation: "sticky combina flujo normal + fijación al umbral.",
  },
  {
    id: "w-exam-hours",
    prompt: "El tiempo total de la prueba técnica es:",
    options: [
      { id: "a", label: "1 hora" },
      { id: "b", label: "2 horas" },
      { id: "c", label: "3 horas" },
      { id: "d", label: "8 horas" },
    ],
    answerId: "c",
    explanation: "Exactamente 3 horas para toda la prueba.",
  },
  {
    id: "w-sessions-count",
    prompt: "¿Cuántas sesiones tiene la prueba en total?",
    options: [
      { id: "a", label: "3 solo prácticas" },
      { id: "b", label: "5 (2 MCQ + 3 prácticas)" },
      { id: "c", label: "10 aleatorias" },
      { id: "d", label: "1 única sesión" },
    ],
    answerId: "b",
    explanation: "2 teóricas + 3 de desarrollo.",
  },
  {
    id: "w-hostlistener",
    prompt: "`@HostListener('keydown.enter')` en una directiva Angular:",
    options: [
      { id: "a", label: "Escucha el evento en el host de la directiva" },
      { id: "b", label: "Crea un FormGroup" },
      { id: "c", label: "Solo funciona con Shadow DOM nativo" },
      { id: "d", label: "Reemplaza zone.js" },
    ],
    answerId: "a",
    explanation: "HostListener enlaza listeners al elemento host.",
  },
];
